= The Assertion Package

== Overview

Assertions are expressed in archetypes in typed first-order predicate logic (FOL). They are used in two places: to express archetype slot constraints, and to express rules in complex object constraints. In both of these places, their role is to constrain something inside the archetype. Constraints on external resources such as terminologies are expressed in the constraint binding part of the archetype terminology, described in Figure <<terminology_package>>. The assertion package is illustrated below in <<rules_package>>.

[.text-center]
.Rules Package
image::{uml_export_dir}/diagrams/AOM-rules.svg[id=rules_package, align="center"]

== Semantics

Archetype assertions are statements which contain the following elements:

* variables, which are inbuilt, archetype path-based, or external query results;
* manifest constants of any primitive type, including the date/time types
* arithmetic operators: +, *, -, /, ^ (exponent), % (modulo division)
* relational operators: >, <, >=, <=, =, !=, matches
* boolean operators: not, and, or, xor
* quantifiers applied to container variables: for_all, exists

A syntax of assertions is defined in the openEHR ADL specification. The package described here is designed to allow the representation of a general-purpose expression tree, as generated by a parser. This relatively simple model of expressions is sufficiently powerful for representing the subset of FOL expressions required in archetypes and templates.

== Class Descriptions

include::{uml_export_dir}/classes/rule_statement.adoc[]
include::{uml_export_dir}/classes/assertion.adoc[]
include::{uml_export_dir}/classes/variable_declaration.adoc[]
include::{uml_export_dir}/classes/expr_variable.adoc[]
include::{uml_export_dir}/classes/builtin_variable.adoc[]
include::{uml_export_dir}/classes/query_variable.adoc[]
include::{uml_export_dir}/classes/expr_item.adoc[]
include::{uml_export_dir}/classes/expr_leaf.adoc[]
include::{uml_export_dir}/classes/expr_constant.adoc[]
include::{uml_export_dir}/classes/expr_constraint.adoc[]
include::{uml_export_dir}/classes/expr_archetype_id_constraint.adoc[]
include::{uml_export_dir}/classes/expr_model_ref.adoc[]
include::{uml_export_dir}/classes/expr_variable_ref.adoc[]
include::{uml_export_dir}/classes/expr_operator.adoc[]
include::{uml_export_dir}/classes/expr_unary_operator.adoc[]
include::{uml_export_dir}/classes/expr_binary_operator.adoc[]
include::{uml_export_dir}/classes/operator_kind.adoc[]

