= The Rules Package

== Overview

The `rules` package defines the model of a generalised notion of 'rules' that can appear in various places in an archetype. Rules in the sense modelled here can be understood as 'declarations' and 'assertions'. Declarations consist of statements defining particular types of variables while assertions consistitute the main substantive kind of rule statement. Assertions are expressed in typed first-order predicate logic (FOPL).

Rules can be used in two places in archetypes. The first is the use of assertions to express archetype slot constraints in instances of the `ARCHETYPE_SLOT` class. The second place is in the archetype `rules` section, where both variable declarataions and assertions are used to express object constraints ranging across multiple nodes, i.e. constraints that can't be expressed 'inline' within the main `definition` section structure. In both of these places, their role is to constrain something _inside_ the current archetype. Constraints on external resources such as terminologies are expressed in the constraint binding part of the archetype `terminology` section, described in Figure <<terminology_package>>. The assertion package is illustrated below.

[.text-center]
.Rules Package
image::{uml_export_dir}/diagrams/AOM-rules.svg[id=rules_package, align="center"]

== Semantics

Archetype assertions are statements which contain the following elements:

* variables, which are inbuilt, archetype path-based, or external query results;
* manifest constants of any primitive type, including the date/time types
* arithmetic operators: `+`, `*`, `-`, `/`, `^` (exponent), `%` (modulo division)
* relational operators: `>`, `<`, `>=`, `\<=`, `=`, `!=`, `matches`
* boolean operators: `not`, `and`, `or`, `xor`
* quantifiers applied to container variables: `for_all`, `exists`

A syntax of assertions is defined in the openEHR ADL specification. The package described here is designed to allow the representation of a general-purpose expression tree, as generated by a parser. This relatively simple model of expressions is sufficiently powerful for representing the subset of FOL expressions required in archetypes and templates.

== Class Descriptions

include::{uml_export_dir}/classes/rule_element.adoc[]
include::{uml_export_dir}/classes/rule_statement.adoc[]
include::{uml_export_dir}/classes/assertion.adoc[]
include::{uml_export_dir}/classes/variable_declaration.adoc[]
include::{uml_export_dir}/classes/expr_variable.adoc[]
include::{uml_export_dir}/classes/builtin_variable.adoc[]
include::{uml_export_dir}/classes/query_variable.adoc[]
include::{uml_export_dir}/classes/expr_item.adoc[]
include::{uml_export_dir}/classes/expr_leaf.adoc[]
include::{uml_export_dir}/classes/expr_constant.adoc[]
include::{uml_export_dir}/classes/expr_constraint.adoc[]
include::{uml_export_dir}/classes/expr_archetype_id_constraint.adoc[]
include::{uml_export_dir}/classes/expr_model_ref.adoc[]
include::{uml_export_dir}/classes/expr_variable_ref.adoc[]
include::{uml_export_dir}/classes/expr_operator.adoc[]
include::{uml_export_dir}/classes/expr_unary_operator.adoc[]
include::{uml_export_dir}/classes/expr_binary_operator.adoc[]
include::{uml_export_dir}/classes/operator_kind.adoc[]

