= The Rules Package

NOTE: the semantics described in this part of the model should not yet be considered stable, as it depends on the openEHR Expression Language, which is still be stabilised.

== Overview

The AOM `rules` package builds upon a subset of the `BASE::org::openehr::expressions` package described in the {openehr_expression}[openEHR Expression Language specification], and adds a small number of classes to express leaf reference types specific to archetypes. This enables expressions to be declared within archetypes that:

* use archetype paths as value references, and;
* include `C_PRIMITIVE_OBJECT` constraints as Boolean-valued sub-expressions.

A special case of the latter is the `C_STRING` leaf constraint type, which is used to represent archetype slot constraints in instances of the `ARCHETYPE_SLOT` class (`_includes_` and `_excludes_` attributes).

The general use of expressions in an archetype is in the `rules` section, where both variable declarataions and assertions are used to express object constraints ranging across multiple nodes, i.e. constraints that can't be expressed 'inline' within the main `definition` section structure. In both of these places, their role is to constrain something _inside_ the current archetype. 

Constraints on external resources such as terminologies are expressed in the constraint binding part in the archetype `terminology`, described in the <<Terminology Package>> section. The AOM `rules` package is illustrated below.

[.text-center]
.Rules Package
image::{uml_export_dir}/diagrams/AOM-rules.svg[id=rules_package, align="center"]

== Semantics

Archetype assertions are expressions which may contain the following elements:

* _constants_:
** _primitive values_: including the date/time types;
** _constraints_ operands, i.e. `C_PRIMITIVE_OBJECT` instances, used as arguments to the `matches` operator;
** _archetype id constraints_, i.e. `C_STRING` instances representing possible archetype identifiers, used in slot constraints.
* any of the openEHR rules operators, i.e.:
** _arithmetic operators_: `+`, `*`, `-`, `/`, `^` (exponent), `%` (modulo division)
** _relational operators_: `>`, `<`, `>=`, `\<=`, `=`, `!=`;
** _boolean operators_: `not`, `and`, `or`, `xor`;
** _quantifiers_ applied to container variables: `for_all`, `exists`;
* _functions_ e.g. basic arithmetic, trigonometric and other functions;
* the following additional semantics:
** _references_ to archetyped values in data, specified by archetype paths.

Variables, assignments, and external queries as described in the main openEHR Rules language are not allowed.

== Class Descriptions

The following classes augment the core model described in the {openehr_expression}[openEHR Expression Language specification].

include::{uml_export_dir}/classes/expr_constraint.adoc[]
include::{uml_export_dir}/classes/expr_archetype_id_constraint.adoc[]
include::{uml_export_dir}/classes/expr_archetype_ref.adoc[]

