= The RM Overlay Package

== Overview

Classes in the `archetype.rm_overlay` package are used to support definition of settings relating to unconstrained RM attributes of constrained object nodes (including the top-level object) within the archetype. The UML model is shown below.

[.text-center]
.RM overlay package
image::{uml_diagrams_uri}/AM-aom2.archetype.rm_overlay.svg[id=rm_overlay, align="center"]

== Semantics

=== RM Attribute Visibility

Currently, the only RM overlay settings are for RM attribute visibility, which is visibility of non-archetyped RM attributes within the context of an archetype. This is described in more detail in the {openehr_am_adl2}#_rm_overlay_section[ADL2 specification^].

The visibility settings consist of a list of per-RM attribute settings, in the form of instances of the class `RM_ATTRIBUTE_VISIBILITY`, each keyed by the RM path to the node(s) to which they apply. The path is formed of an object node path within the archetype follwed by a path to an RM attribute not already included in the archetype structure. The former part is one of:

* the root path, `/`;
* an object path within the archetyped structure e.g. `/items[id20]`.

The latter part is a path containing no object identifiers (id-codes), of one or mode RM attribute names from the Reference Model. The terminal attribute name will almost always be a single-valued attribute, since the visibility of container attributes will almost always be defined in terms of specifically constrained child objects, i.e. part of the archetyped structure.

RM visibility can be specified in two ways. First, in terms of attribute visibility within modelling tools, using the values `show` and `hide`. A non-archetyped RM attribute is by default no visible within an archetype modelling tool visualisation, since it is not part of the archetyped structure. The only means of displaying such an attrbute is to display all non-archetyped RM attributes in some generic fashion. Setting the visibility on a particular RM attribute path to `show` indicates to the tool that this RM attribute should be displayed, along with the archetyped structure - preferably in a visually distinct way. This enables modellers to see specific model attributes that are built into the RM, and do not need to be modelled as archetype objects.

The `hide` setting is to allow a `show` setting for an attribute's visibility in a specialisation parent to be reversed in the current archetype. The visibility setting for an RM attribute with respect to the specialisation lineage (aka inheritance hierarchy) is just the most recent setting.

==== Validity

A second visibility setting is an optional _alias_, which is specified in the form of an ad-code (similar to an id-code) whose definition is found in the `terminology` section of the archetype, in the usual fashion. Definition of an alias enables an RM attribute node to be multi-lingually renamed from its default RM name. If the `_alias_` attribute is set, the `_visibility_` must also be set. Normally this should be set to `show`, ahtough the value is not currently mandated, in order to allow possible extension of visibility settings beyond just `show` and `hide`.

== Class Descriptions

include::{uml_export_dir}/classes/rm_overlay.adoc[]
include::{uml_export_dir}/classes/rm_attribute_visibility.adoc[]
include::{uml_export_dir}/classes/visibility_type.adoc[]


