= Model Overview

The model described here is a pure object-oriented model that can be used with archetype parsers and software that manipulates archetypes and templates in memory. It is typically the output of a parser of any serialsed form of archetypes. It is dependent on the openEHR Base package `assumed_types` package, which states the assumed primitive types for the AOM. These types are similar to those found in most programming and schema languages. This package is shown below.

[.text-center]
.base_types.assumed_types Package
image::{uml_export_dir}/diagrams/BASE-base_types.assumed_types.svg[id=base_types_assumed_types, align="center"]

NOTE: the above package does not constitute a formal part of this specification. Any implementation of the AOM will typically have to use such types within languages and/or libraries.

== Package Structure

The Archetype Object Model is defined as the package `am.archetype` , as illustrated in Figure [[aom_package_overview]]. It is shown in the context of the `am.archetype` packages.

[.text-center]
.Package Overview
image::{uml_export_dir}/diagrams/AOM-packages.svg[id=aom_package_overview, align="center"]

== Definition and Utility Classes

=== Overview

Various definitional classes are used in the AOM. Some are defined in the `aom.definitions` package from the AM component, while others come from the `definitions` package from the openEHR BASE component. These are illustrated below.

[.text-center]
.Definition Package
image::{uml_export_dir}/diagrams/AOM-definitions.svg[id=definition_package, align="center"]

The enumeration type `VALIDITY_KIND` is provided in order to define standard values representing `mandatory`, `optional`, or `disallowed` in any model. It is used in this model in classes such as `C_DATE` , `C_TIME` and `C_DATE_TIME`. The `VERSION_STATUS` enumeration type serves a similar function within various AOM types.

Other classes used from the `base` package include `AUTHORED_RESOURCE` (openEHR `resource` package) and its subordinate classes. These are shown in full within the packages that use them.

=== Class Definitions

include::{uml_export_dir}/classes/version_status.adoc[]

include::{uml_export_dir}/classes/validity_kind.adoc[]

include::{uml_export_dir}/classes/adl_code_definitions.adoc[]

