include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Primary Author

* Thomas Beale, Ars Semantica, UK; openEHR International Board.

=== Contributors

This specification has benefited from input from the openEHR and wider health informatics community. The openEHR Foundation would like to recognise the following people and institutions.

* Sebastian Garde PhD, Ocean Informatics
* Heather Leslie MD, Ocean Informatics
* Ian McNicoll MD, MSc, Ocean Informatics UK
* Martin van der Meer, Code24, Netherlands
* David Moner PhD, Universitat Politècnica de València, Spain
* Erik Sundvall PhD, Linkoping University, Sweden

=== Trademarks

* 'openEHR' is a registered trademark of The openEHR Foundation
* 'SNOMED CT' is a registered trademark of IHTSDO

=== Supporters

The work reported in this paper has been funded by the following organisations:

* the {openehr_industry_partners}[openEHR Industry Partners^];
* Better d.o.o, Slovenia
* Ocean Informatics, UK
== Conformance

Conformance of a data or software artifact to an openEHR specification is determined by a formal test of that artifact against the relevant {openehr_its_component}[openEHR Implementation Technology Specification(s) (ITSs)^], such as an IDL interface or an XML-schema. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.

== Tools

Various tools exist for creating and processing archetypes. The {openehr_awb}[ADL Workbench^] is a reference compiler, visualiser and editor. The openEHR tools can be {modelling_tools}[downloaded from the website^]. Source projects can be found at the {openehr_git}[openEHR Github project^].


:sectnums!:

include::partial$amendment_record.adoc[]
