include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Primary Author

* Thomas Beale, Ocean Informatics UK; openEHR Foundation Management Board

=== Contributors

This specification has benefited from input from the openEHR and wider health informatics community. The openEHR Foundation would like to recognise the following people and institutions.

* Sebastian Garde, PhD, Ocean Informatics
* Heather Leslie MD, Ocean Informatics
* Ian McNicoll MD, MSc, Ocean Informatics UK
* Martin van der Meer, Code24, Netherlands
* David Moner PhD, Universitat Politècnica de València, Spain

=== Trademarks

* 'openEHR' is a registered trademark of The openEHR Foundation
* 'SNOMED CT' is a registered trademark of IHTSDO

=== Supporters

The work reported in this document was funded by:

* Ocean Informatics.
== Tools

Various tools exist for creating and processing archetypes. The http://www.openehr.org/downloads/ADLworkbench/home[ADL Workbench] is a reference compiler, visualiser and editor. The openEHR tools can be http://www.openehr.org/downloads/modellingtools[downloaded from the website]. Source projects can be found at the https://github.com/openEHR[openEHR Github project].


:sectnums!:

include::partial$amendment_record.adoc[]
