[appendix]
= Syntax Specification

The normative specification of the ADL1.4 syntax is expressed in Antlr4 as a series of component grammars, shown below. This has been tested with the Antlr4.5 implementation available from http://www.antlr.org[Antlr.org^]. The source files are available on Github in the {openehr_adl_antlr}/tree/master/src/main/antlr/adl14[adl-antlr repository^]. The ODIN grammar used in ADL archetypes described in the {openehr_odin}[openEHR ODIN specification^].

== ADL Outer Syntax

The following grammar expresses the outer syntax of ADL, i.e. the top-level structure of section keywords and initial identification lines in an ADL text.

[source, antlr-java]
--------
include::{grammar_dir}/adl14/adl.g4[]
--------

== cADL Syntax

The following grammar expresses the syntax of cADL composite types, i.e. the language of the `definition` section of an archetype.

[source, antlr-java]
--------
include::{grammar_dir}/adl14/cadl.g4[]
--------

== cADL Primitives Syntax

The following grammar defines the syntax of cADL primitives, which are used by cADL composites and also by ADL rules.

[source, antlr-java]
--------
include::{grammar_dir}/adl14/cadl_primitives.g4[]
--------

== Rules Syntax

The following grammar defines the syntax that may appear in the `rules` section of an archetype and also the assertions in Archetype slots.

[source, antlr-java]
--------
include::{grammar_dir}/adl14/adl_rules.g4[]
--------

== ODIN structures

The following grammar defines the syntax for ODIN structures.

[source, antlr-java]
--------
include::{grammar_dir}/adl14/odin.g4[]
--------

== ODIN value types

The following grammar defines the syntax for the terminal types in ADL, which are derived from ODIN.

[source, antlr-java]
--------
include::{grammar_dir}/adl14/odin_values.g4[]
--------

== Base Patterns

The following grammar defines syntax of generic base patterns.

[source, antlr-java]
--------
include::{grammar_dir}/adl14/base_patterns.g4[]
--------

== Base Lexer

The following grammar defines common lexical entities.

[source, antlr-java]
--------
include::{grammar_dir}/adl14/base_lexer.g4[]
--------
