= Preface

== Purpose

This document describes the design basis and syntax of the Archetype Definition Language 1.4 (ADL 1.4). It is intended for software developers, technically-oriented domain specialists and subject matter experts (SMEs). ADL is designed as an abstract human-readable and computer-processible syntax. ADL archetypes can be hand-edited using a normal text editor.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* The open source healthcare community;
* Solution vendors;
* Medical informaticians and clinicians interested in health information.

== Related Documents

Prerequisite documents for reading this document include:

* The openEHR Architecture Overview (<<openehr_overview>>);
* The openEHR Archetype Technical Overview (<<openehr_am_overview>>)

Related documents include:

* The openEHR Archetype Object Model (AOM14) (<<openehr_am_adl14>>);

== Nomenclature

In this document, the term 'attribute' denotes any stored property of a type defined in an object model, including primitive attributes and any kind of relationship such as an association or aggregation. XML 'attributes' are always referred to explicitly as 'XML attributes'.

== Status

This specification is in the STABLE state. The development version of this document can be found at http://www.openehr.org/releases/AM/latest/ADL1.4.html.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content. Feedback should be provided either on the http://lists.openehr.org/mailman/listinfo/openehr-technical_lists.openehr.org[technical mailing list], or on the https://openehr.atlassian.net/browse/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].

NOTE: this specification is a re-formatted issue of the http://www.openehr.org/releases/1.0.2/architecture/am/adl.pdf[original ADL 1.4 Specification from openEHR Release 1.0.2]. There are slight changes in formatting, citations and other references, corrections to typographical errors and changed syntax colourisation due to the use of more modern language-based syntax colourisers in the publishing tools.

NOTE: for users requiring the most recent form of ADL and archteype technology in general, the http://www.openehr.org/programs/specification/releases/currentbaseline#ADL2[Archetype Definition Language 2 (ADL2) specifications should be used]. In particular, the http://www.openehr.org/releases/AM/latest/Overview.html[Archetype Technology Overview] should be referred to for the most current state of Archetype Technology.

== Tools

Various tools exist for creating and processing archetypes. The http://www.openehr.org/downloads/ADLworkbench/home[ADL Workbench] is a reference compiler, visualiser and editor. The openEHR tools can be http://www.openehr.org/downloads/modellingtools[downloaded from the website] .
Source projects can be found at the https://github.com/openEHR[openEHR Github project].
