= Preface

== Purpose

This document describes the design basis and syntax of the Archetype Definition Language 1.4 (ADL 1.4). It is intended for software developers, technically-oriented domain specialists and subject matter experts (SMEs). ADL is designed as an abstract human-readable and computer-processible syntax. ADL archetypes can be hand-edited using a normal text editor.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* The open source healthcare community;
* Solution vendors;
* Medical informaticians and clinicians interested in health information.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview];
* The {openehr_am_overview}[openEHR Archetype Technical Overview].

Related documents include:

* The {openehr_am_adl14}[openEHR Archetype Object Model (AOM14)].

== Nomenclature

In this document, the term 'attribute' denotes any stored property of a type defined in an object model, including primitive attributes and any kind of relationship such as an association or aggregation. XML 'attributes' are always referred to explicitly as 'XML attributes'.

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_am_adl14}.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content. Feedback should be provided either on the {openehr_technical_list}[technical mailing list], or on the {openehr_jira}/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].

NOTE: this specification is a re-formatted issue of the http://www.openehr.org/releases/1.0.2/architecture/am/adl1.4.pdf[original ADL 1.4 Specification from openEHR Release 1.0.2]. There are slight changes in formatting, citations and other references, corrections to typographical errors and changed syntax colourisation due to the use of more modern language-based syntax colourisers in the publishing tools.

NOTE: for users requiring the most recent form of ADL and archteype technology in general, the {openehr_am}[Archetype Definition Language 2 (ADL2) specifications should be used]. In particular, the {openehr_am_overview}[Archetype Technology Overview] should be referred to for the most current state of Archetype Technology.

== Tools

Various tools exist for creating and processing archetypes. The {openehr_awb}[ADL Workbench] is a reference compiler, visualiser and editor. The openEHR tools can be http://www.openehr.org/downloads/modellingtools[downloaded from the website] .
Source projects can be found at the {openehr_git}[openEHR Github project].
