==== C_DATE Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*C_DATE*

|*Description*
{set:cellbgcolor:lightblue}
2+|ISO 8601-compatible constraint on instances of Date in the form either of a set of validity values, or else date ranges based on the C_ORDERED list constraint. There is no validity flag for ‘year’, since it must always be by definition mandatory in order to have a sensible date at all. Syntax expressions of instances of this class include “YYYY-??-??” (date with optional month and day).
{set:cellbgcolor!}

|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*month_validity*: `VALIDITY_KIND`
{set:cellbgcolor!}
|Validity of month in constrained date.

|
{set:cellbgcolor:lightblue}
|*day_validity*: `VALIDITY_KIND`
{set:cellbgcolor!}
|Validity of day in constrained date.

|
{set:cellbgcolor:lightblue}
|*timezone_validity*: `VALIDITY_KIND`
{set:cellbgcolor!}
|Validity of timezone in constrained date.

|*Invariant*
{set:cellbgcolor:lightblue}
2+|*_Pattern_validity_*: pattern /= Void implies valid_iso8601_date_constraint_pattern(pattern)
{set:cellbgcolor!}
|===
