==== C_DATE_TIME Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*C_DATE_TIME*

|*Description*
{set:cellbgcolor:lightblue}
2+|ISO 8601-compatible constraint on instances of Date_Time. There is no validity flag for ‘year’, since it must always be by definition mandatory in order to have a sensible date/time at all. Syntax expressions of instances of this class include “YYYY-MM-DDT??:??:??” (date/time with optional time) and “YYYY-MMDDTHH:MM:xx” (date/time, seconds not allowed).
{set:cellbgcolor!}

|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*month_validity*: `VALIDITY_KIND`
{set:cellbgcolor!}
|Validity of month in constrained date.

|
{set:cellbgcolor:lightblue}
|*day_validity*: `VALIDITY_KIND`
{set:cellbgcolor!}
|Validity of day in constrained date.

|
{set:cellbgcolor:lightblue}
|*timezone_validity*: `VALIDITY_KIND`
{set:cellbgcolor!}
|Validity of timezone in constrained date.

|
{set:cellbgcolor:lightblue}
|*minute_validity*: `VALIDITY_KIND`
{set:cellbgcolor!}
|Validity of minute in constrained time.

|
{set:cellbgcolor:lightblue}
|*second_validity*: `VALIDITY_KIND`
{set:cellbgcolor!}
|Validity of second in constrained time.

|
{set:cellbgcolor:lightblue}
|*millisecond_validity*: `VALIDITY_KIND`
{set:cellbgcolor!}
|Validity of millisecond in constrained time.

|*Invariant*
{set:cellbgcolor:lightblue}
2+|*_Pattern_validity_*: pattern /= Void implies valid_iso8601_date_time_constraint_pattern(pattern)
{set:cellbgcolor!}
|===
