==== C_ORDERED Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*_C_ORDERED (abstract)_*

|*Description*
{set:cellbgcolor:lightblue}
2+|Abstract parent of primitive constrainer classes based on ORDERED base types, i.e. types like Integer, Real, and the Date/Time types. The model constraint is a List of Intervals, which may include point Intervals, and acts as a efficient and formally tractable representation of any number of point values and/or contiguous intervals of an ordered value domain. +
In its simplest form, the constraint accessor returns just a single point Interval<T> object, representing a single value. +
The next simplest form is a single proper Interval <T> (i.e. normal two-sided or half-open interval). The most complex form is a list of any combination of point and proper intervals.
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|C_PRIMITIVE_OBJECT
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*1..1 +
(redefined)*
{set:cellbgcolor:lightblue}
|*constraint*: `List<Interval<T>>`
{set:cellbgcolor!}
|
|===
