==== SIBLING_ORDER Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*SIBLING_ORDER*

|*Description*
{set:cellbgcolor:lightblue}
2+|Defines the order indicator that can be used on a C_OBJECT within a container attribute in a specialised archetype to indicate its order with respect to a sibling defined in a higher specialisation level. +
Misuse: This type cannot be used on a C_OBJECT other than one within a container attribute in a specialised archetype.
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*1..1*
{set:cellbgcolor:lightblue}
|*is_before*: `Boolean`
{set:cellbgcolor!}
|True if the order relationship is ‘before’, if False, it is ‘after’.

|*1..1*
{set:cellbgcolor:lightblue}
|*sibling_node_id*: `String`
{set:cellbgcolor!}
|Node identifier of sibling before or after which this node should come.
|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*is_after*: `Boolean`
{set:cellbgcolor!}
|True if the order relationship is ‘after’, computed as the negation of is_before.
|===
