include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Primary Author

* Thomas Beale, Ocean Informatics UK; openEHR Foundation Management Board

=== Trademarks

* 'Microsoft' and '.Net' are registered trademarks of the Microsoft Corporation.
* 'Java' is a registered trademark of Oracle Corporation
* 'Linux' is a registered trademark of Linus Torvalds.
* 'openEHR' is a registered trademark of The openEHR Foundation
* 'SNOMED CT' is a registered trademark of IHTSDO
== Tools

Various tools exist for creating and processing archetypes. The http://www.openehr.org/downloads/ADLworkbench/home[ADL Workbench] is a reference compiler, visualiser and editor. The openEHR tools can be http://www.openehr.org/downloads/modellingtools[downloaded from the website] .
Source projects can be found at the https://github.com/openEHR[openEHR Github project].

== Relationship to OPT '1.4'
This specification describes an Operational Template based on ADL2/AOM2, rather than the original OPT, which is an XML-schema format based on ADL 1.4 archetypes.


:sectnums!:

include::partial$amendment_record.adoc[]
