=== ARCHETYPE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*ARCHETYPE*

h|*Description*
2+a|Archetype equivalent to ARCHETYPED class in Common reference model. Defines semantics of identfication, lifecycle, versioning, composition and specialisation.

h|*Inherit*
2+|`AUTHORED_RESOURCE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*definition*: `C_COMPLEX_OBJECT`
a|Root node of the definition of this archetype.

h|*1..1*
|*ontology*: `ARCHETYPE_ONTOLOGY`
a|The ontology of the archetype.

h|*0..1*
|*adl_version*: `String`
a|ADL version if archetype was read in from an ADL sharable archetype.

h|*1..1*
|*archetype_id*: `ARCHETYPE_ID`
a|Multi-axial identifier of this archetype in archetype space.

h|*0..1*
|*uid*: `HIER_OBJECT_ID`
a|OID identifier of this archetype.

h|*1..1*
|*concept*: `String`
a|The normative meaning of the archetype as a whole, expressed as a local archetype code, typically “at0000”.

h|*0..1*
|*parent_archetype_id*: `ARCHETYPE_ID`
a|Identifier of the specialisation parent of this archetype.

h|*0..1*
|*invariants*: `List<ASSERTION>`
a|Invariant statements about this object. Statements are expressed in first order predicate logic, and usually refer to at least two attributes.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*concept_name* ( +
a_lang: `String[1]` +
): `String` +
*_post-condition_*: `Result.is_equal (definition.node_id)`
a|The concept name of the archetype in language a_lang; corresponds to the term definition of the concept attribute in the archetype ontology.

h|
|*physical_paths* (): `List<String>`
a|Set of language-independent paths extracted from archetype. Paths obey Xpath-like syntax and are formed from alternations of C_OBJECT.node_id and C_ATTRIBUTE.rm_attribute_name values.

h|
|*logical_paths* ( +
lang: `String[1]` +
): `List<String>`
a|Set of language-dependent paths extracted from archetype. Paths obey the same syntax as physical_paths, but with node_ids replaced by their meanings from the ontology.

h|
|*specialisation_depth* (): `Integer` +
*_post-condition_*: `Result = terminology.specialisation_depth`
a|Specialisation depth of this archetype; larger than 0 if this archetype has a parent. Derived from terminology.specialisation_depth.

h|
|*is_specialised* (): `Boolean` +
*_post-condition_*: `Result implies parent_archetype_id /= Void`
a|True if this archetype is a specialisation of another.

h|
|*is_valid* (): `Boolean` +
*_Post_*: `not (node_ids_valid and internal_references_valid and constraint_references_valid) implies not Result`
a|True if the archetype is valid overall; various tests should be used, including checks on node_ids, internal references, and constraint references.

h|
|*node_ids_valid* (): `Boolean`
a|True if every node_id found on a C_OBJECT node is found in ontology.term_codes.

h|
|*previous_version* (): `String`
a|Version of predecessor archetype of this archetype, if any.

h|
|*internal_references_valid* (): `Boolean`
a|True if every ARCHETYPE_INTERNAL_REF. target_path refers to a legitimate node in the archetype definition.

h|
|*constraint_references_valid* (): `Boolean`
a|True if every CONSTRAINT_REF.reference found on a C_OBJECT node in the archetype definition is found in ontology.constraint_codes.

h|
|*short_concept_name* (): `String`
a|The short concept name of the archetype extracted from the archetype_id.

h|
|*version* (): `String`
a|

h|*Invariants*
2+a|*_Inv_concept_valid_*: `ontology.has_term_code (concept_code)`

h|
2+a|*_Inv_specialisation_validity_*: `is_specialised implies specialisation_depth > 0`

h|
2+a|*_Inv_invariants_valid_*: `invariants /= Void implies not invariants.is_empty`

h|
2+a|*_Inv_uid_validity_*: `uid /= Void implies not uid.is_empty`

h|
2+a|*_Inv_version_validity_*: `version /= Void and then version.is_equal(archetype_id.version_id)`

h|
2+a|*_Inv_description_valid_*: `description /= Void`

h|
2+a|*_Inv_original_language_valid_*: `original_language /= void and then language /= Void`
|===
