=== C_DATE_TIME Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*C_DATE_TIME*

h|*Description*
2+a|ISO 8601-compatible constraint on instances of Date_Time. There is no validity flag for ‘year’, since it must always be by definition mandatory in order to have a sensible date/time at all. Syntax expressions of instances of this class include “YYYY-MM-DDT??:??:??” (date/time with optional time) and “YYYY-MMDDTHH:MM:xx” (date/time, seconds not allowed).

h|*Inherit*
2+|C_PRIMITIVE

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*month_validity*: `VALIDITY_KIND`
a|

h|*0..1*
|*day_validity*: `VALIDITY_KIND`
a|

h|*0..1*
|*hour_validity*: `VALIDITY_KIND`
a|

h|*0..1*
|*minute_validity*: `VALIDITY_KIND`
a|

h|*0..1*
|*second_validity*: `VALIDITY_KIND`
a|

h|*0..1*
|*millisecond_valdity*: `VALIDITY_KIND`
a|

h|*0..1*
|*timezone_valdity*: `VALIDITY_KIND`
a|

h|*0..1*
|*range*: `Interval<ISO8601_DATE_TIME>`
a|

h|*0..1 +
(redefined)*
|*assumed_value*: `ISO8601_DATE_TIME`
a|

h|*Invariant*
2+a|*_Pattern_validity_*: pattern /= Void implies valid_iso8601_date_time_constraint_pattern(pattern)
|===
