=== C_DEFINED_OBJECT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_C_DEFINED_OBJECT (abstract)_*

h|*Description*
2+a|Abstract parent type of C_OBJECT subtypes that are defined by value, i.e. whose definitions are actually in the archetype rather than being by reference.

h|*Inherit*
2+|`C_OBJECT`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*assumed_value*: `Any`
a|Value to be assumed if none sent in data.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*valid_value* ( +
a_value: `Any[1]` +
): `Boolean`
a|True if a_value is valid with respect to constraint expressed in concrete instance of this type.

h|
|*prototype_value* (): `Any`
a|Generate a prototype value from this constraint object.

h|
|*has_assumed_value* (): `Boolean`
a|True if there is an assumed value.

h|
|*default_value* (): `Any`
a|Generate a default value from this constraint object.

h|
|*any_allowed* (): `Boolean` +
*_Post_*: `Result = attributes.is_empty`
a|True if any value of the reference model type being constrained is allowed. Redefine in descendants.

h|*Invariants*
2+a|*_Assumed_value_valid_*: `has_assumed_value implies valid_value(assumed_value)`
|===
