=== DV_IDENTIFIER Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_IDENTIFIER*

h|*Description*
2+a|Type for representing identifiers of real-world entities. Typical identifiers include drivers licence number, social security number, veterans affairs number, prescription id, order id, and so on.

DV_IDENTIFIER is used to represent any identifier of a real thing, issued by some authority or agency.

Misuse: DV_IDENTIFIER is not used to express identifiers generated by the infrastructure to refer to information items; the types OBJECT_ID and OBJECT_REF and subtypes are defined for this purpose.

h|*Inherit*
2+|`DATA_VALUE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*issuer*: `String`
a|Optional authority which issues the kind of id used in the id field of this object.

h|*0..1*
|*assigner*: `String`
a|Optional organisation that assigned the id to the item being identified.

h|*1..1*
|*id*: `String`
a|The identifier value. Often structured, according to the definition of the issuing authority's rules.

h|*0..1*
|*type*: `String`
a|Optional identifier type, such as  prescription , or  Social Security Number . One day a controlled vocabulary might be possible for this.

h|*Invariants*
2+a|*_Issuer_valid_*: `not issuer.is_empty`

h|
2+a|*_Assigner_valid_*: `not assigner.is_empty`

h|
2+a|*_Id_valid_*: `not id.is_empty`

h|
2+a|*_Type_valid_*: `not type.is_empty`
|===
