=== DV_MULTIMEDIA Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_MULTIMEDIA*

h|*Description*
2+a|A specialisation of DV_ENCAPSULATED for audiovisual and biosignal types. Includes further metadata relating to multimedia types which are not applicable to other subtypes of DV_ENCAPSULATED.

h|*Inherit*
2+|`DV_ENCAPSULATED`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*alternate_text*: `String`
a|Text to display in lieu of multimedia display/replay.

h|*0..1*
|*uri*: `DV_URI`
a|URI reference to electronic information stored outside the record as a file, database entry etc, if supplied as a reference.

h|*0..1*
|*data*: `Byte`
a|The actual data found at uri, if supplied inline.

h|*1..1*
|*media_type*: `CODE_PHRASE`
a|Data media type coded from openEHR code set  media types  (interface for the IANA MIME types code set).

h|*0..1*
|*compression_algorithm*: `CODE_PHRASE`
a|Compression type, a coded value from the openEHR  Integrity check  code set. Void means no compression.

h|*0..1*
|*integrity_check*: `Byte`
a|Binary cryptographic integrity checksum.

h|*0..1*
|*integrity_check_algorithm*: `List<CODE_PHRASE>`
a|Type of integrity check, a coded value from the openEHR  Integrity check  code set.

h|*0..1*
|*thumbnail*: `DV_MULTIMEDIA`
a|The thumbnail for this item, if one exists; mainly for graphics formats.

h|*1..1*
|*size*: `Integer`
a|Original size in bytes of unencoded encapsulated data. I.e. encodings such as base64, hexadecimal etc do not change the value of this attribute.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*is_external* (): `Boolean`
a|Computed from the value of the uri attribute: True if  the data is stored externally to the record, as indicated by `uri'. A copy may also be stored internally, in which case `is_expanded' is also true.

h|
|*is_inline* (): `Boolean`
a|Computed from the value of the data attribute. True if  the  data is stored  in  expanded  form, ie within the EHR itself.

h|
|*is_compressed* (): `Boolean`
a|Computed from the value of the compression_algorithm attribute: True if  the  data is stored  in  compressed form.

h|
|*has_integrity_check* (): `Boolean`
a|Computed from the value of the integrity_check_algorithm attribute: True if an integrity check has been computed.

h|*Invariants*
2+a|*_Not_empty_*: `is_inline or is_external`

h|
2+a|*_Media_type_valid_*: `media_type /= Void and then code_set (Code_set_id_media_types).has_code (media_type)`

h|
2+a|*_Compression_algorithm_validity_*: `compression_algorithm /= Void implies code_set (Code_set_id_compression_algorithms).has_code (compression_algorithm)`

h|
2+a|*_Integrity_check_validity_*: `integrity_check /= Void implies integrity_check_algorithm /= Void`

h|
2+a|*_Integrity_check_algorithm_validity_*: `integrity_check_algorithm /= Void implies code_set (Code_set_id_integrity_check_algorithms).has_code (integrity_check_algorithm)`

h|
2+a|*_Size_valid_*: `size >= 0`
|===
