=== DV_PERIODIC_TIME_SPECIFICATION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_PERIODIC_TIME_SPECIFICATION*

h|*Description*
2+a|Specifies periodic points in time, linked to the calendar (phase-linked), or a real world repeating event, such as  breakfast  (event-linked). Based on the HL7v3 data types PIVL<T> and EIVL<T>.

Used in therapeutic prescriptions, expressed as INSTRUCTIONs in the openEHR model.

h|*Inherit*
2+|`DV_TIME_SPECIFICATION`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*period* (): `DV_DURATION`
a|The period of the repetition, computationally derived from the syntax representation. Extracted from the  value' attribute.

h|(effected)
|*calendar_alignment* (): `String`
a|Calendar alignment extracted from value.

h|(effected)
|*event_alignment* (): `String`
a|Event alignment extracted from value.

h|(effected)
|*institution_specified* (): `Boolean`
a|Extracted from value.

h|*Invariants*
2+a|*_Value_valid_*: `value.formalism.is_equal (“HL7:PIVL”) or value.formalism. is_equal (“HL7:EIVL”)`
|===
