=== DV_PROPORTION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_PROPORTION*

h|*Description*
2+a|Models a ratio of values, i.e. where the numerator and denominator are both pure numbers. The valid_proportion_kind property of the PROPORTION_KIND class is
used to control the type attribute to be one of a defined set.

Used for recording titers (e.g. 1:128), concentration ratios, e.g. Na:K (unitary denominator), albumin:creatinine ratio, and percentages, e.g. red cell distirbution width (RDW).

Misuse: Should not be used to represent things like blood pressure which are often written using a  '/' character, giving the misleading impression that the item is a ratio, when in fact it is a structured value. Similarly, visual acuity, often written as (e.g.) “6/24” in clinical notes is not a ratio but an ordinal (which includes non-numeric symbols like CF = count fingers etc). Should not be used for formulations.

h|*Inherit*
2+|`PROPORTION_KIND`, `DV_AMOUNT`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*numerator*: `Real`
a|Numerator of ratio

h|*1..1*
|*denominator*: `Real`
a|Denominator of ratio.

h|*1..1*
|*type*: `Integer`
a|Indicates semantic type of proportion, including percent, unitary etc.

h|*0..1*
|*precision*: `Integer`
a|Precision  to  which  the  numerator and denominator values of  the  proportion are expressed, in terms of number  of  decimal places. The value 0 implies an integral quantity. The value -1 implies no limit, i.e. any number of decimal places.

h|*0..1 +
(redefined)*
|*normal_range*: `DV_INTERVAL<DV_PROPORTION>`
a|Optional normal range.

h|*0..1 +
(redefined)*
|*other_reference_ranges*: `List<REFERENCE_RANGE<DV_PROPORTION>>`
a|Optional tagged other reference ranges for this value in its particular measurement context.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(effected)
|*magnitude* (): `Real`
a|Effective magnitude represented by ratio.

h|
|*is_integral* (): `Boolean`
a|True if the numerator and denominator values are integers, i.e. if the precision is 0.

h|(redefined)
|*infix =* ( +
source: `DV_PROPORTION[1]` +
): `DV_PROPORTION`
a|Assignment operator

h|*Invariants*
2+a|*_Type_validity_*: `valid_proportion_kind (type)`

h|
2+a|*_Precision_validity_*: `precision = 0 implies is_integral`

h|
2+a|*_Is_integral_validity_*: `is_integral implies (numerator.floor = numerator and denominator.floor = denominator)`

h|
2+a|*_Fraction_validity_*: `(type = pk_fraction or type = pk_integer_fraction) implies is_integral`

h|
2+a|*_Unitary_validity_*: `type = pk_unitary implies denominator = 1`

h|
2+a|*_Percent_validity_*: `type = pk_percent implies denominator = 100`

h|
2+a|*_Valid_denominator_*: `denominator /= 0.0`
|===
