=== DV_TEXT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_TEXT*

h|*Description*
2+a|A text item, which may contain any amount of legal characters arranged as e.g. words, sentences etc (i.e. one DV_TEXT may be more than one word). Visual formatting and hyperlinks may be included.

A DV_TEXT can be  coded  by adding mappings to it.

Fragments of text, whether coded or not are used on their own as values, or to make up larger tracts of text which may be marked up in some way, eventually going to make up paragraphs.

h|*Inherit*
2+|`DATA_VALUE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*value*: `String`
a|Displayable rendition of the item, regardless of its underlying structure. For DV_CODED_TEXT, this is the rubric of the complete term as provided by the terminology service. No carriage returns, line feeds, or other non-printing characters permitted.

h|*0..1*
|*hyperlink*: `DV_URI`
a|Optional link sitting behind a section of plain text or coded term item.

h|*0..1*
|*formatting*: `String`
a|A format string of the form  name:value; name:value... , e.g. "font-weight : bold; font-family : Arial; font-size : 12pt;".

Values taken from W3C CSS2 properties lists  back-ground  and  font .

h|*0..1*
|*mappings*: `List<TERM_MAPPING>`
a|Terms from other terminologies most closely matching this term, typically used where the originator (e.g. pathology lab) of information uses a local terminology but also supplies one or more equivalents from well known terminologies (e.g. LOINC).

h|*0..1*
|*language*: `CODE_PHRASE`
a|Optional indicator of the localised language in which the value is written. Coded from openEHR Code Set  languages . Only used when either the text object is in a different language from the enclosing ENTRY, or else the text object is being used outside of an ENTRY or other enclosing structure which indicates the language.

h|*0..1*
|*encoding*: `CODE_PHRASE`
a|Name of character encoding scheme in which this value is encoded. Coded from openEHR Code Set  character sets . Unicode is the default assumption in openEHR, with UTF-8 being the assumed encoding. This attribute allows for variations from these assumptions.

h|*Invariants*
2+a|*_Valid_value_*: `not value.is_empty and then not (value.has(CR) or value.has(LF))`

h|
2+a|*_Language_valid_*: `language /= Void implies code_set (Code_set_id_languages).has_code (language)`

h|
2+a|*_Encoding_valid_*: `encoding /= Void implies code_set (Code_set_id_character_sets).has_code (encoding)`

h|
2+a|*_Mappings_valid_*: `mappings /= void implies not mappings.is_empty`

h|
2+a|*_Formatting_valid_*: `formatting /= void implies not formatting.is_empty`
|===
