=== DV_TIME_SPECIFICATION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_DV_TIME_SPECIFICATION (abstract)_*

h|*Description*
2+a|This is an abstract class of which all timing specifications are specialisations. Specifies points in time, possibly linked to the calendar, or a real world repeating event, such as  breakfast.

h|*Inherit*
2+|`DATA_VALUE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*value*: `DV_PARSABLE`
a|The specification, in the HL7v3 syntax for PIVL or EIVL types.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(abstract)
|*calendar_alignment* (): `String`
a|Indicates what prototypical point in the calendar the specification is aligned to, e.g.  5th of the month . Empty if not aligned. Extracted from the  value' attribute.

h|(abstract)
|*event_alignment* (): `String`
a|Indicates what real-world event the specification is aligned to if any. Extracted from the  value' attribute.

h|(abstract)
|*institution_specified* (): `Boolean`
a|Indicates if the specification is aligned with institution schedules, e.g. a hospital nursing changeover or meal serving times. Extracted from the  value' attribute.
|===
