=== DV_URI Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DV_URI*

h|*Description*
2+a|A reference to an object which conforms to the Universal Resource Identifier (URI) standard. See "Universal Resource Identifiers in WWW" by Tim Berners-Lee at http://www.ietf.org/rfc/rfc3986.txt. This  is  a  World-Wide  Web  RFC for  global identification  of resources.
See http://www.w3.org/Addressing for a starting point on URIs.

h|*Inherit*
2+|`DATA_VALUE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*value*: `String`
a|Value of URI as a String.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*scheme* (): `String`
a|A distributed information "space" in which  information objects  exist. The scheme simultaneously specifies an information space and a mechanism for accessing objects in  that  space.  For  example  if  scheme  = "ftp", it identifies the information space in which  all  ftpable objects  exist,  and also the application - ftp - which can be used to access them. Values may include: "ftp", "telnet", "mailto", "gopher" and  many others. Refer to WWW URI RFC for a full list. New information spaces can be accommodated  within  the URI specification.

h|
|*path* (): `String`
a|A string whose format is  a  function  of  the  scheme. Identifies   the   location  in  <scheme>-space  of  an information entity. Typical values include hierarchical directory  paths  for  any  machine.  For example, with scheme = "ftp", path might be /pub/images/image_01. The strings "." and ".." are reserved for use in the path. Paths may include internet/intranet location identifiers of the form: sub_domain...domain, e.g. "info.cern.ch"

h|
|*fragment_id* (): `String`
a|A part of, a  fragment  or  a  sub-function  within  an object. Allows references to sub-parts of objects, such as a certain line and character  position  in  a  text object. The  syntax  and semantics are defined by the application responsible for the object.

h|
|*query* (): `String`
a|Query string to send to application implied  by  scheme and  path.  Enables  queries  to applications, including databases  to  be  included in  the  URI. Supports any query meaningful to the server, including SQL.

h|*Invariants*
2+a|*_Value_valid_*: `not value.is_empty`
|===
