=== EHR Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*EHR*

h|*Description*
2+a|The EHR object is the root object and access point of an EHR for a subject of care.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*system_id*: `HIER_OBJECT_ID`
a|The id of the EHR repository on which this EHR was created.

h|*1..1*
|*ehr_id*: `HIER_OBJECT_ID`
a|The id of this EHR.

h|*0..1*
|*contributions*: `List<OBJECT_REF>`
a|List of contributions causing changes to this EHR. Each contribution contains a list of versions, which may include references to any number of VERSION instances, i.e. items of type VERSIONED_COMPOSITION and VERSIONED_FOLDER.

h|*1..1*
|*ehr_status*: `OBJECT_REF`
a|Reference to EHR_STATUS object for this EHR.

h|*1..1*
|*ehr_access*: `OBJECT_REF`
a|Reference to EHR_ACCESS object for this EHR.

h|*0..1*
|*compositions*: `List<OBJECT_REF>`
a|Master list of all Versioned Composition references in this EHR.

h|*0..1*
|*directory*: `OBJECT_REF`
a|Optional directory structure for this EHR.

h|*1..1*
|*time_created*: `DV_DATE_TIME`
a|Time of creation of the EHR.

h|*Invariants*
2+a|*_Contributions_valid_*: `contributions.for_all (c &#124; c.type.is_equal(“CONTRIBUTION”))`

h|
2+a|*_Ehr_access_valid_*: `ehr_access.type.is_equal (“VERSIONED_EHR_ACCESS”)`

h|
2+a|*_Ehr_status_valid_*: `ehr_status.type.is_equal(“VERSIONED_EHR_STATUS”)`

h|
2+a|*_Compositions_valid_*: `compositions.for_all (c &#124; c.type.is_equal (“VERSIONED_COMPOSITION”))`

h|
2+a|*_Directory_valid_*: `directory /= Void implies directory.type.is_equal (“VERSIONED_FOLDER”)`
|===
