=== EXTRACT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*EXTRACT*

h|*Description*
2+a|Generic model of an Extract of some information from a repository.

h|*Inherit*
2+|`LOCATABLE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*chapters*: `List<EXTRACT_CHAPTER>`
a|The content extracted and serialised from the source repository for this Extract.

h|*0..1*
|*specification*: `EXTRACT_SPEC`
a|The specification that this Extract actually conforms to; might not be identical with the specification of the corresponding request.

h|*0..1*
|*request_id*: `HIER_OBJECT_ID`
a|Reference to causing Request, if any.

h|*1..1*
|*time_created*: `DV_DATE_TIME`
a|Creation time of this Extract

h|*1..1*
|*system_id*: `HIER_OBJECT_ID`
a|Identifier of creating system.

h|*1..1*
|*sequence_nr*: `Integer`
a|Number of this Extract response in sequence of responses to Extract request identified by request_id. If this is the sole response, or there was no request, value is 1.

h|*0..1*
|*participations*: `List<EXTRACT_PARTICIPATION>`
a|Participations relevant to the creation of this Extract.

h|*Invariants*
2+a|*_Sequence_nr_valid_*: `sequence_nr >= 1`
|===
