=== EXTRACT_UPDATE_SPEC Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*EXTRACT_UPDATE_SPEC*

h|*Description*
2+a|Specification of the how the request should be processed by server. The request can be persisted in the server, meaning that a) it can be re-activated by the requesting system simply by indicating Request id, and b) that a changes-only pattern of Extract updates can be set up. To achieve this, the server has to remember what was sent in the previous response.

The update mode may be event-driven and periodic update or a mixture of both. The candidate items to be sent each time are the result of re-evaluating the content and versioning parts of the specification; what is actually sent is determined by the send_changes_only flag.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*persist_in_server*: `Boolean`
a|If True, this Request is persisted in the server until further notice.

h|*0..1*
|*repeat_period*: `DV_DURATION`
a|Period for resending update Extracts in response to original Request.

h|*0..1*
|*trigger_events*: `List<DV_CODED_TEXT>`
a|Set of Event names that will cause sending of update Extracts. Event types include:

* any_change - any change in content items matched by content specification, e.g. new versions of persistent compositions. If the content list allows matching of any, or a wide range of archetypes, this event type will match any additions to the record.
* correction - match error corrections only, including deletions.
* update - match updates (i.e. new versions) of included content items.

Coded by openEHR Terminology group "extract update trigger event type".

h|*1..1*
|*update_method*: `CODE_PHRASE`
a|Indicate mode of update. Can be: send only items that are changed (including logical deletions) or new since last send. For persist_in_server Requests only.

h|*Invariants*
2+a|*_Overall_validity_*: `repeat_period /= Void or trigger_events /= Void`

h|
2+a|*_Trigger_events_validity_*: `trigger_events /= Void implies not trigger_events.is_empty`

h|
2+a|*_Send_changes_only_validity_*: `send_changes_only implies persist_in_server`
|===
