=== EXTRACT_VERSION_SPEC Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*EXTRACT_VERSION_SPEC*

h|*Description*
2+a|Specification of what versions should be included in an Extract. By default, only latest versions are included in the Extract, in which case this part of the Extract specification is not needed at all. The attributes include_all_versions and commit_time_interval are used to modify this; the former forces all versions to be included; the latter limits the versions to be those latest versions committed in the time interval, or if include_all_versions is True, all versions committed in the time interval.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*include_all_versions*: `Boolean`
a|True if all versions of each item in the Extract are included.

h|*0..1*
|*commit_time_interval*: `DV_INTERVAL<DV_DATE_TIME>`
a|Specifies commit time interval of items to source repository to include in Extract. By default, only latest versions whose commit times fall in the range are included. If include_all_versions is True, then the range includes all versions committed within the interval.

h|*1..1*
|*include_revision_history*: `Boolean`
a|True if revision histories of the items in the Extract are included. If included, it is always the full revision history.

h|*1..1*
|*include_data*: `Boolean`
a|True if the data of items matched by the content spec should be included. This is the default. If False, only revision history is included in serialised versions. Turning this option on in openEHR systems causes X_VERSIONED_OBJECTs to have revision_history set, but versions Void. Useful for interrogating a server without having to look at any content data. In other systems it may or may not have a sensible meaning.

h|*Invariants*
2+a|*_Includes_revision_history_valid_*: `not include_data implies include_revision_history`
|===
