=== EXTRACT_CONTENT_ITEM Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_EXTRACT_CONTENT_ITEM (abstract)_*

h|*Description*
2+a|Abstract model of a wrapper for one content item in an Extract, containing various meta-data. Indicates whether it was part of the primary set and what its original path was. Intended to be subtyped for wrappers of specific types of content.

h|*Inherit*
2+|`EXTRACT_ITEM`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*is_primary*: `Boolean`
a|True if the content item carried in this container was part of the primary set for the Extract, i.e. not added due to link-following.

h|*0..1*
|*is_changed*: `Boolean`
a|True if the content item carried in this container is any kind of change since last send, in repeat sending situations.

h|*0..1*
|*is_masked*: `Boolean`
a|True if the content of this item has not been included due to insufficient access rights of requestor.

h|*0..1*
|*item*: `Any`
a|Content object.

h|*Invariants*
2+a|*_Item_validity_*: `is_masked xor item /= Void`
|===
