=== EXTRACT_PARTICIPATION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*EXTRACT_PARTICIPATION*

h|*Description*
2+a|Model of a participation of a Party (any Actor or Role) in an activity.  Used to represent any participation of a Party in some activity, which is not  explicitly in the model, e.g. assisting nurse. Can be used to record past or  future participations.

Should not be used in place of more permanent relationships between demographic entities.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*time*: `DV_INTERVAL<DV_DATE_TIME>`
a|The time interval during which the participation took place, if it is used in an observational context (i.e. recording facts about the past); or the intended time interval of the participation when used in future contexts, such as EHR Instructions.

h|*1..1*
|*function*: `DV_TEXT`
a|The function of the Party in this participation (note that a given party might participate in more than one way in a particular activity). This attribute should be coded, but cannot be limited to the HL7v3:ParticipationFunction vocabulary, since it is too limited and hospital-oriented.

h|*0..1*
|*mode*: `DV_CODED_TEXT`
a|The mode of the performer / activity interaction, e.g. present, by telephone, by email etc.

h|*1..1*
|*performer*: `String`
a|Uid of demographic entity within Extract who performed this participation.

h|*Invariants*
2+a|*_Function_valid_*: `function /= Void and then function.generating_type.is_equal (“DV_CODED_TEXT”) implies terminology (Terminology_id_openehr).has_code_for_group_id (Group_id_participation_function, function.defining_code)`

h|
2+a|*_Mode_valid_*: `mode /= Void and terminology (Terminology_id_openehr).has_code_for_group_id (Group_id_participation_mode, mode.defining_code)`
|===
