=== FEEDER_AUDIT_DETAILS Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*FEEDER_AUDIT_DETAILS*

h|*Description*
2+a|Audit details for any system in a feeder system chain. Audit details here means the general notion of who/where/when the information item to which the audit is attached was created. None of the attributes is defined as mandatory, however, in different scenarios, various combinations of attributes will usually be mandatory. This can be controlled by specifying feeder audit details in legacy archetypes.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*system_id*: `String`
a|Identifier of the system which handled the information item.

h|*0..1*
|*location*: `PARTY_IDENTIFIED`
a|Identifier of the particular site/facility within an organisation which handled the item. For computability, this identifier needs to be e.g. a PKI identifier which can be included in the identifier list of the PARTY_IDENTIFIED object.

h|*0..1*
|*subject*: `PARTY_PROXY`
a|Identifiers for subject of the received information item.

h|*0..1*
|*provider*: `PARTY_IDENTIFIED`
a|Optional provider(s) who created, committed, forwarded or otherwise handled the item.

h|*0..1*
|*time*: `DV_DATE_TIME`
a|Time of handling the item. For an originating system, this will be time of creation, for an intermediate feeder system, this will be a time of accession or other time of handling, where available.

h|*0..1*
|*version_id*: `String`
a|Any identifier used in the system such as  "interim" ,  "final" , or numeric versions if available.

h|*Invariants*
2+a|*_System_id_valid_*: `not system_id.is_empty`
|===
