=== INTERVAL_EVENT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*INTERVAL_EVENT*

h|*Description*
2+a|Defines a single interval event in a series.

h|*Inherit*
2+|`EVENT`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*width*: `DV_DURATION`
a|Length of the interval during which the state was true. Void if an instantaneous event.

h|*0..1*
|*sample_count*: `Integer`
a|Optional count of original samples to which this event corresponds.

h|*1..1*
|*math_function*: `DV_CODED_TEXT`
a|Mathematical function of the data of this event, e.g.  maximum ,  mean  etc. Coded using openEHR Terminology group  event math function.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*interval_start_time* (): `DV_DATE_TIME`
a|Start time of the interval of this event.

h|*Invariants*
2+a|*_Math_function_validity_*: `terminology (Terminology_id_openehr).has_code_for_group_id (Group_id_event_math_function, math_function.defining_code)`

h|
2+a|*_Interval_start_time_valid_*: `interval_start_time = time - width`
|===
