=== ORIGINAL_VERSION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*ORIGINAL_VERSION*

h|*Description*
2+a|A Version containing locally created content and optional attestations.

h|*Inherit*
2+|`VERSION`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*uid*: `OBJECT_VERSION_ID`
a|Stored version of inheritance precursor.

h|*0..1*
|*preceding_version_uid*: `OBJECT_VERSION_ID`
a|Stored version of inheritance precursor.

h|*0..1*
|*other_input_version_uids*: `List<OBJECT_VERSION_ID>`
a|Identifiers of other versions whose content was merged into this version, if any.

h|*1..1*
|*lifecycle_state*: `DV_CODED_TEXT`
a|Lifecycle state of the content item in this version.

h|*0..1*
|*attestations*: `List<ATTESTATION>`
a|Set of attestations relating to this version.

h|*0..1*
|*data*: `T`
a|
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*is_merged* (): `Boolean`
a|True if this Version was created from more than just the preceding (checked out) version.

h|*Invariants*
2+a|*_Attestations_valid_*: `attestations /= Void implies not attestations.is_empty`

h|
2+a|*_Is_merged_validity_*: `other_input_version_ids = Void xor is_merged`

h|
2+a|*_Other_input_version_uids_valid_*: `other_input_version_uids /= Void implies not other_input_version_uids.is_empty`
|===
