=== PROPORTION_KIND Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*PROPORTION_KIND*

h|*Description*
2+a|Class of enumeration constants defining types of proportion for the DV_PROPORTION class.

h|*Constants*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*pk_ratio*: `Integer{nbsp}={nbsp}0`
a|Ratio type. Numerator and denominator may be any value.

h|*1..1*
|*pk_unitary*: `Integer{nbsp}={nbsp}1`
a|Denominator must be 1.

h|*1..1*
|*pk_percent*: `Integer{nbsp}={nbsp}2`
a|Denominator is 100, numerator is understood as a percentage value.

h|*1..1*
|*pk_fraction*: `Integer{nbsp}={nbsp}3`
a|Numerator and denominator are integral, and the presentation method uses a slash, e.g.  1/2 .

h|*1..1*
|*pk_integer_fraction*: `Integer{nbsp}={nbsp}4`
a|Numerator and denominator are integral, and the presentation method uses a slash, e.g.  1/2 ; if the numerator is greater than the denominator, e.g. n=3, d=2, the presentation is  1 1/2 .
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*valid_proportion_kind* ( +
nq: `Integer[1]` +
): `Boolean`
a|True if n is one of the defined types.
|===
