=== RESOURCE_DESCRIPTION_ITEM Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*RESOURCE_DESCRIPTION_ITEM*

h|*Description*
2+a|Language-specific detail of resource description. When a resource is translated for use in another language environment, each RESOURCE_DESCRIPTION_ITEM needs to be copied and translated into the new language.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*language*: `CODE_PHRASE`
a|The localised language in which the items in this description item are written. Coded from openEHR Code Set  languages .

h|*1..1*
|*purpose*: `String`
a|Purpose of the resource.

h|*0..1*
|*keywords*: `List<String>`
a|Keywords which characterise this resource, used e.g. for indexing and searching.

h|*0..1*
|*use*: `String`
a|Description of the uses of the resource, i.e. contexts in which it could be used.

h|*0..1*
|*misuse*: `String`
a|Description of any misuses of the resource, i.e. contexts in which it should not be used.

h|*0..1*
|*copyright*: `String`
a|Optional copyright statement for the resource as a knowledge resource.

h|*0..1*
|*original_resource_uri*: `Hash<String, String>`
a|URIs of original clinical document(s) or description of which resource is a formalisation, in the language of this description item; keyed by meaning.

h|*0..1*
|*other_details*: `Hash<String, String>`
a|Additional language-senstive resource metadata, as a list of name/value pairs.

h|*Invariant*
2+a|*_Language_valid_*: code_set (Code_set_id_languages).has_code (language)

h|
2+a|*_Purpose_valid_*: not purpose.is_empty

h|
2+a|*_Use_valid_*: use /= Void implies not use.is_empty

h|
2+a|*_misuse_valid_*: misuse /= Void implies not misuse.is_empty

h|
2+a|*_copyright_valid_*: copyright /= Void implies not copyright.is_empty
|===
