=== VERSION Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*_VERSION (abstract)_*

h|*Description*
2+a|Abstract model of one Version within a Version container, containing data, commit audit trail, and the identifier of its Contribution.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*contribution*: `OBJECT_REF`
a|Contribution in which this version was added.

h|*0..1*
|*signature*: `String`
a|OpenPGP digital signature or digest of content committed in this Version.

h|*1..1*
|*commit_audit*: `AUDIT_DETAILS`
a|Audit trail corresponding to the committal of this version to the VERSIONED_OBJECT.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*uid*: `OBJECT_VERSION_ID`
a|Unique identifier of this VERSION, in the form of an {object_id, a version_tree_id, creating_system_id} triple, where the object_id has the same value as the containing VERSIONED_OBJECT's uid.

h|
|*preceding_version_uid*: `OBJECT_VERSION_ID`
a|Unique identifier of the version of which this version is a modification; Void if this is the first version.

h|
|*data*: `T`
a|Original content of this Version.

h|
|*lifecycle_state*: `DV_CODED_TEXT`
a|Lifecycle state of this version; coded by openEHR vocabulary version lifecycle state .

h|
|*canonical_form*: `String`
a|Canonical form of Version object, created by serialising all attributes except
signature.

h|
|*owner_id*: `HIER_OBJECT_ID` +
*_Post_*: Result.value.is_equal (uid.object_id.value)
a|Copy of the owning VERSIONED_OBJECT.uid value; extracted from the local uid property's object_id.

h|
|*is_branch*: `Boolean`
a|True if this Version represents a branch. Derived from uid attribute.

h|*Invariant*
2+a|*_Preceding_version_uid_validity_*: uid.version_tree_id.is_first xor preceding_version_uid /= Void

h|
2+a|*_Lifecycle_state_ valid_*: lifecycle_state /= Void and then terminology (Term_id_openehr).has_code_for_group_id (Group_id_version_lifecycle_state, lifecycle_state.defining_code)
|===
