= The Specifications

The semantics described above are defined in the following set of specifications:

*{openehr_am_id}[Archetype Identification^]*:: a normative specification of archetype and template model identification, versioning, referencing and lifecycle;
*{openehr_am_adl2}[The Archetype Definition Language (ADL)^]*:: a normative abstract syntax for archetypes, templates and terminology binding;
*{openehr_am_aom2}[The Archetype Object Model (AOM)^]*:: the normative structural model of archetypes and templates;
*{openehr_am_opt2}[The Operational Template (OPT)^]*:: normative description of the semantics of Operational Templates (OPTs);
*{openehr_query_aql}[The Archetype Querying Language (AQL)^]*:: the normative querying language based on archetypes and terminology.

The first specification above describes the semantics of Archetype identifiers, which is equivalent to describing the structure of the Archetype-based model space. It also describes aspects of lifecycle management and versioning of Archetypes.

The Archetype Definition Language (ADL) is a formal abstract syntax for archetypes, and can be used to provide a default serial expression of archetypes. It is the *primary document for human understanding of the semantics of archetypes*.

The AOM is the definitive formal expression of archetype semantics, and is independent of any particular syntax. The *main purpose of the AOM specification is to specify to developers how to build archetype tools* and also EHR components that use archetypes.

The semantics defined in the AOM are used to express the object structures of source archetypes and flattened archetypes. Since in ADL 2 a template is just a kind of archetype, the AOM also describes the semantics of templates as well. The two source forms are authored by users via tools, while the two flat forms are generated by tools. The rules for how to use the AOM for each of these forms is described in details in this specification.

The Operational Template specification defines the operational form of openEHR Templates, used in downstream systems and tools. This is primarily useful to tool-builders.

Lastly, the Archetype Query Language (AQL) specification defines a query language that assumes a Reference Model and Archetypes as its semantic base.

The remainder of this document provides further high level description of the Archetype-based model environment, essential for understanding the formal specifications.
