[appendix]
= Syntax Specification

The normative specification of the ADL syntax is expressed in Antlr4 as a series of component grammars, shown below. This has been tested with the Antlr4.5 implementation available from http://www.antlr.org[Antlr.org^]. The source files are available on Github - {openehr_adl_antlr}/tree/master/src/main/antlr/adl2[adl-antlr repository^]. The ODIN grammar used in ADL archetypes described in the {openehr_odin}[openEHR ODIN specification^].

There are various other syntax specifications in existence.

The http://www.openehr.org/downloads/ADLworkbench/home[ADL Workbench^] currently implements a version of the ADL2 language and syntax expressed in traditional yacc/lex specifications, with the `.y` and `.l` files are found in the following locations:

* https://github.com/openEHR/adl-tools/tree/master/components/adl_compiler/src/syntax/adl/parser[ADL outer syntax^]
* https://github.com/openEHR/adl-tools/tree/master/components/adl_compiler/src/syntax/cadl/parser[cADL and rules syntax^]
* https://github.com/wolandscat/EOMF/tree/master/library/odin/parser[ODIN^]

The above grammars are complete and more heavily tested, but due to being in an older technology, not easily re-usable by other languages, or by LL(*) parser generators like Antlr, since they contain various LR (left recursive) constructs.

An https://github.com/openEHR/adl2-core/tree/master/adl-parser/src/main/resources/antlr3/org/openehr/adl/antlr[Antlr3 grammar specification^] also exists and is used in the current Java implementation of AOM2/ADL2.

== ADL Outer Syntax

The following grammar expresses the outer syntax of ADL, i.e. the top-level structure of section keywords and initial identification lines in an ADL text.

[source, antlr-java]
--------
include::{grammar_dir}/adl2/adl.g4[]
--------

== cADL Syntax

The following grammar expresses the syntax of cADL composite types, i.e. the language of the `definition` section of an archetype.

[source, antlr-java]
--------
include::{grammar_dir}/adl2/cadl.g4[]
--------

== cADL Primitives Syntax

The following grammar defines the syntax of cADL primitives, which are used by cADL composites and also by ADL rules.

[source, antlr-java]
--------
include::{grammar_dir}/adl2/cadl_primitives.g4[]
--------

== Rules Syntax

The following grammar defines the syntax that may appear in the `rules` section of an archetype and also the assertions in Archetype slots.

[source, antlr-java]
--------
include::{grammar_dir}/adl2/adl_rules.g4[]
--------

== ADL Keywords

The following grammar defines the lexer patterns for ADL keywords.

[source, antlr-java]
--------
include::{grammar_dir}/adl2/adl_keywords.g4[]
--------

== ODIN structures

The following grammar defines the syntax for ODIN structures.

[source, antlr-java]
--------
include::{grammar_dir}/adl2/odin.g4[]
--------

== ODIN value types

The following grammar defines the syntax for the terminal types in ADL, which are derived from ODIN.

[source, antlr-java]
--------
include::{grammar_dir}/adl2/odin_values.g4[]
--------

== Base Expressions

The following grammar defines syntax of expressions.

[source, antlr-java]
--------
include::{grammar_dir}/adl2/base_expressions.g4[]
--------

== Base Patterns

The following grammar defines syntax of generic base patterns.

[source, antlr-java]
--------
include::{grammar_dir}/adl2/base_patterns.g4[]
--------

== Base Lexer

The following grammar defines lexer patterns of generic lexical tokens.

[source, antlr-java]
--------
include::{grammar_dir}/adl2/base_lexer.g4[]
--------
