== Specialise Section

This optional section indicates that the archetype is a specialisation of some other archetype, whose identity must be given. Only one specialisation parent is allowed, i.e. an archetype cannot 'multiply-inherit' from other archetypes. An example of declaring specialisation is as follows:

[source, adl]
--------
archetype (adl_version=2.4.0; rm_release=1.0.2)
    org.openehr::openEHR-EHR-OBSERVATION.cbc.v1.0.0
specialise 
    openEHR-EHR-OBSERVATION.haematology.v1
--------

The parent is designated by a reference, normally including the major version only. A reference without a namespace, as above, denotes an archetype in the same namespace as the specialised archetype; a reference to a parent in another namespace includes that namespace. See {openehr_base_artefact_identification}#_between_specialised_archetypes[Artefact Identification^] for the rules.

Note that both the US and British English versions of the word "specialise" are valid in ADL.

The following syntax validity rule applies in the specialisation section:

[.rule]
SASID: archetype specialisation parent identifier validity. for specialised artefacts, the identifier of the specialisation parent must conform to the reference (`hrid_ref`) syntax defined in the {openehr_base_artefact_identification}#_referencing[openEHR Artefact Identification specification^].
