= Preface

== Purpose

The purpose of this document is to describe an identification system for openEHR archetypes (including templates). This includes archetypes created by any organisation, including the openEHR Foundation, standards bodies and clinical modelling initiatives and government programmes.

The semantics covered include:

* formal human-readable and machine identifiers;
* versioning;
* lifecycle management and states;
* referencing artefacts from elsewhere;
* deal with transfer and forking;
* supporting integrity and non-repudiation.

Unless otherwise stated, in this document, the term 'artefact' refers specifically to these artefact types.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview].
* The {openehr_am_overview}[openEHR Archetypes Technical Overview].
* The {openehr_base_types}[openEHR Base Types Specification].

Related documents include:

* The {openehr_am_aom2}[openEHR Archetype Object Model 2 (AOM2) Specification].
* The {openehr_am_adl2}[openEHR Archetype Description Language (ADL2) Specification].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_am_id}[{openehr_domain}/releases/AM/latest/identification.html].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the {openehr_technical_list}[technical mailing list], or on the {openehr_jira_prs_am}[specifications issue tracker].

== Tools

Various tools exist for creating and processing archetypes. The {openehr_awb}[ADL Workbench] is a reference compiler, visualiser and editor. The openEHR tools can be {modelling_tools}[downloaded from the website]. Source projects can be found at the {openehr_git}[openEHR Github project].

