= Introduction

== Purpose

The purpose of this document is to describe an identification system for health informatics knowledge artefacts, including archetype, template and terminology subsets. This includes such artefacts created by organisations such as the openEHR Foundation, standards bodies and clinical modelling initiatives.

The semantics covered include:

* formal human-readable and machine identifiers;
* versioning;
* lifecycle management and states;
* referencing artefacts from elsewhere;
* deal with transfer and forking;
* supporting integrity and non-repudiation.

Unless otherwise stated, in this document, the term 'artefact' refers specifically to these artefact types.

== Related Documents

Prerequisite documents for reading this document include:

* The http://www.openehr.org/releases/trunk/architecture/overview.pdf[openEHR Architecture Overview]
* The http://www.openehr.org/releases/trunk/architecture/am/archetype_technical_overview.pdf[openEHR Archetypes Technical Overview]

Related documents include:

* The http://www.openehr.org/releases/trunk/architecture/am/aom2.pdf[Archetype Object Model (AOM2)]
* The http://www.openehr.org/releases/trunk/architecture/am/adl2.pdf[Archetype Description Language (ADL2)]

== Status

This specification is in the Trial state. The development version of this document can be found at http://www.openehr.org/releases/trunk/architecture/am/knowledge_id_system.pdf.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the http://lists.openehr.org/mailman/listinfo/openehr-technical_lists.openehr.org[technical mailing list], or on the https://openehr.atlassian.net/browse/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].

== Tools

Various tools exist for creating and processing archetypes. The http://www.openehr.org/downloads/ADLworkbench/home[ADL Workbench] is a reference compiler, visualiser and editor. The openEHR tools can be http://www.openehr.org/downloads/modellingtools[downloaded from the website]. Source projects can be found at the https://github.com/openEHR[openEHR Github project].

