= Preface

== Purpose

The purpose of this document is to describe an identification system for openEHR archetypes (including templates). This includes archetypes created by any organisation, including the openEHR Foundation, standards bodies and clinical modelling initiatives and government programmes.

The semantics covered include:

* formal human-readable and machine identifiers;
* versioning;
* lifecycle management and states;
* referencing artefacts from elsewhere;
* deal with transfer and forking;
* supporting integrity and non-repudiation.

Unless otherwise stated, in this document, the term 'artefact' refers specifically to these artefact types.

== Related Documents

Prerequisite documents for reading this document include:

* The openEHR Architecture Overview (<<openehr_overview>>).
* The openEHR Archetypes Technical Overview (<<openehr_am_overview>>).

Related documents include:

* The Archetype Object Model (AOM2) (<<openehr_am_aom>>).
* The Archetype Description Language (ADL2) (<<openehr_am_adl>>).

== Status

This specification is in the Development state. The development version of this document can be found at http://www.openehr.org/releases/AM/latest/Identification.html.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the http://lists.openehr.org/mailman/listinfo/openehr-technical_lists.openehr.org[technical mailing list], or on the https://openehr.atlassian.net/browse/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].

== Tools

Various tools exist for creating and processing archetypes. The http://www.openehr.org/downloads/ADLworkbench/home[ADL Workbench] is a reference compiler, visualiser and editor. The openEHR tools can be http://www.openehr.org/downloads/modellingtools[downloaded from the website]. Source projects can be found at the https://github.com/openEHR[openEHR Github project].

