= Primitive Package

== Overview

Ultimately any archetype definition will devolve down to leaf node constraints on instances of primitive types. The `primitive` package, illustrated in the following figure, defines the semantics of constraint on such types.

[.text-center]
.aom14.archetype.constraint_model.primitive Package
image::{uml_diagrams_uri}/AM-aom14.archetype.constraint_model.primitive.svg[id=constraint_model.primitive_package, align="center"]

Most of the types provide at least two alternative ways to represent the constraint; for example the `C_DATE` type allows the constraint to be expressed in the form of a pattern (defined in the ADL specification) or an `Interval<Date>`. Note that the interval form of dates is probably only useful for historical date checking (e.g. the date of an antique or a particular batch of vaccine), rather than constraints on future date/times.

== Class Descriptions

include::{uml_export_dir}/classes/{pkg}c_primitive.adoc[]
include::{uml_export_dir}/classes/{pkg}c_boolean.adoc[]
include::{uml_export_dir}/classes/{pkg}c_string.adoc[]
include::{uml_export_dir}/classes/{pkg}c_integer.adoc[]
include::{uml_export_dir}/classes/{pkg}c_real.adoc[]
include::{uml_export_dir}/classes/{pkg}c_date.adoc[]
include::{uml_export_dir}/classes/{pkg}c_time.adoc[]
include::{uml_export_dir}/classes/{pkg}c_date_time.adoc[]
include::{uml_export_dir}/classes/{pkg}c_duration.adoc[]
