[appendix]
= Reference Model Dependencies

The following shows Reference Model extracts relevant to the AOM.

== RM 1.0.2 support.assumed_types package

[.text-center]
.Release 1.0.2 RM support.assumed_types package
image::{uml_aom14_diagrams_uri}/BASE-base_types.assumed_types.svg[id=rm_support_iassumed_types_package, align="center"]

== RM 1.0.2 support.identification package

[.text-center]
.Release 1.0.2 RM support.identification package
image::{uml_aom14_diagrams_uri}/RM-support.identification.svg[id=rm_support_id_package, align="center"]

== RM 1.0.2 data_types.basic package

[.text-center]
.Release 1.0.2 RM data_types.basic package
image::{uml_aom14_diagrams_uri}/RM-data_types.basic.svg[id=rm_data_types_basic_package, align="center"]

== RM 1.0.2 data_types.text package

[.text-center]
.Release 1.0.2 RM data_types.text package
image::{uml_aom14_diagrams_uri}/RM-data_types.text.svg[id=rm_data_types_text_package, align="center"]

== RM 1.0.2 data_types.quantity package

[.text-center]
.Release 1.0.2 RM data_types.quantity package
image::{uml_aom14_diagrams_uri}/RM-data_types.quantity.svg[id=rm_data_types_quantity_package, align="center"]

== RM 1.0.2 common.resource package

[.text-center]
.Release 1.0.2 RM common.resource package
image::{uml_aom14_diagrams_uri}/RM-common.resource.svg[id=rm_common_resource_package, align="center"]

include::{uml_export_dir}/AOM1.4/classes/authored_resource.adoc[]
include::{uml_export_dir}/AOM1.4/classes/translation_details.adoc[]
include::{uml_export_dir}/AOM1.4/classes/resource_description.adoc[]
include::{uml_export_dir}/AOM1.4/classes/resource_description_item.adoc[]