=== ADL_CODE_DEFINITIONS Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*ADL_CODE_DEFINITIONS*

h|*Description*
2+a|Definitions relating to the internal code system of archetypes.

h|*Constants*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*Id_code_leader*: `String{nbsp}={nbsp}"id"`
a|String leader of ‘identifier’ codes, i.e. codes used to identify archteype nodes.

h|*1..1*
|*Value_code_leader*: `String{nbsp}={nbsp}"at"`
a|String leader of ‘value’ codes, i.e. codes used to identify codes values, including value set members.

h|*1..1*
|*Value_set_code_leader*: `String{nbsp}={nbsp}"ac"`
a|String leader of ‘value set’ codes, i.e. codes used to identify value sets.

h|*1..1*
|*Specialisation_separator*: `char{nbsp}={nbsp}'.'`
a|Character used to separate numeric parts of codes belonging to different specialisation levels.

h|*1..1*
|*Code_regex_pattern*: `String{nbsp}={nbsp}"(0&#124;[1-9][0-9]&#42;)(\.(0&#124;[1-9][0-9]&#42;))&#42;"`
a|Regex used to define the legal numeric part of any archetype code. Corresponds to the simple pattern of dotted numbers, as used in typical multi-level numbering schemes.

h|*1..1*
|*Root_code_regex_pattern*: `String{nbsp}={nbsp}"^id1(\.1)&#42;$"`
a|Regex pattern of the root id code of any archetype. Corresponds to codes of the form id1, id1.1, id1.1.1 etc..
|===
