=== ARCHETYPE_CONSTRAINT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_ARCHETYPE_CONSTRAINT (abstract)_*

h|*Description*
2+a|Abstract parent of all constraint model types. Defines conformance and congruence function signatures.

h|*Inherit*
2+|`ADL_CODE_DEFINITIONS`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*parent*: `ARCHETYPE_CONSTRAINT`
a|Parent node, except in the case of the top of a tree, i.e. root `C_COMPLEX_OBJECT` of an archetype definition.

h|*0..1*
|*soc_parent*: `C_SECOND_ORDER`
a|Inverse relationship for `ARCHETYPE_CONSTRAINT` node owned by `C_SECOND_ORDER._members_` attribute.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*is_prohibited* (): `Boolean`
a|True if this node is prohibited. Implemented in subtypes.

h|
|*has_path* ( +
a_path: `String[1]` +
): `boolean`
a|True if the relative path a_path exists at this node.

h|
|*path* (): `String`
a|Path of this node relative to root of archetype.

h|
|*c_conforms_to* ( +
other: `ARCHETYPE_CONSTRAINT[1]`, +
rmcc: `FUNCTION<<String,String>,Boolean>[1]` +
): `Boolean`
a|True if constraints represented by this node, ignoring any sub-parts, are narrower or the same as other.
Typically used during validation of special-ised archetype nodes.

.Parameters +
[horizontal]
`_rmcc_`:: RM conformance checker - a lambda (i.e. function object) that can compute conformance of type-names within the  Reference Model on which the current archetype is based. The signature provides two arguments representing respectively, the `_rm_type_name_` of the current node and the `_rm_type_name_` of the node being redefined in a specialisation parent archetype.

h|
|*c_congruent_to* ( +
other: `ARCHETYPE_CONSTRAINT[1]` +
): `Boolean`
a|True if constraints represented by this node contain no further redefinitions with respect to the node other, with the exception of node_id redefnition in `C_OBJECT` nodes.

Typically used to test if an inherited node locally contains any constraints.

h|
|*is_second_order_constrained* (): `Boolean` +
*_Post_*: `soc_parent /= Void or else (parent /= Void and then parent.is_second_order_constrained)`
a|True if there is a second order constraint such as a tuple constraint on this node.

h|
|*is_root* (): `Boolean`
a|True if this node is the root of the tree.

h|
|*is_leaf* (): `Boolean`
a|True if this node is a terminal node in the tree structure, i.e. having no child nodes.
|===
