=== ARCHETYPE_CONSTRAINT Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*_ARCHETYPE_CONSTRAINT (abstract)_*

h|*Description*
2+a|Archetype equivalent to LOCATABLE class in openEHR Common reference model. Defines common constraints for any inheritor of LOCATABLE in any reference model.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*parent*: `ARCHETYPE_CONSTRAINT`
a|Parent node, except in the case of the top of a tree, i.e. root C_COMPLEX_OBJECT of an archetype definition.

h|*0..1*
|*soc_parent*: `C_SECOND_ORDER`
a|Inverse relationship for ARCHETYPE_CONSTRAINT node owned by C_SECOND_ORDER.members attribute.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*is_prohibited*: `Boolean`
a|True if this node (and all its sub-nodes) is a valid archetype node for its type. This function should be implemented by each subtype to perform semantic validation of itself, and then call the is_valid function in any subparts, and generate the result appropriately.

h|
|*has_path* (a_path: `String`): `boolean`
a|True if the relative path a_path exists at this node.

h|
|*path*: `String`
a|Path of this node relative to root of archetype.

h|
|*c_conforms_to* (other: `ARCHETYPE_CONSTRAINT`): `Boolean`
a|True if constraints represented by this node, ignoring any sub-parts, are narrower or the same as other.
Typically used during validation of special-ised archetype nodes.

h|
|*c_congruent_to* (other: `ARCHETYPE_CONSTRAINT`): `Boolean`
a|True if constraints represented by this node contain no further redefinitions with respect to the node other, with the exception of node_id redefnition in C_OBJECT nodes.
Typically used to test if an inherited node locally contains any constraints.

h|
|*is_second_order_constrained*: `Boolean` +
*_Post_*: soc_parent /= Void or else (parent /= Void and then parent.is_second_order_constrained)
a|True if there is a second order constraint such as a tuple constraint on this node.

h|
|*is_root*: `Boolean`
a|

h|
|*is_leaf*: `Boolean`
a|
|===
