=== ARCHETYPE_SLOT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*ARCHETYPE_SLOT*

h|*Description*
2+a|Constraint describing a  slot' where another archetype can occur.

h|*Inherit*
2+|`<<_c_object_class,C_OBJECT>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*includes*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_archetype_id_constraint_class,ARCHETYPE_ID_CONSTRAINT>>>`
a|List of constraints defining other archetypes that could be included at this point.

h|*0..1*
|*excludes*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_archetype_id_constraint_class,ARCHETYPE_ID_CONSTRAINT>>>`
a|List of constraints defining other archetypes that cannot be included at this point.

h|*1..1*
|*is_closed*: `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if this slot specification in this artefact is closed to further filling either in further specialisations or at runtime. Default value False, i.e. unless explicitly set, a slot remains open.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*any_allowed* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if no constraints stated, and slot is not closed.
|===
