=== C_ARCHETYPE_ROOT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*C_ARCHETYPE_ROOT*

h|*Description*
2+a|A specialisation of C_COMPLEX_OBJECT whose node_id attribute is an archetype identifier rather than the normal internal node code (i.e. id-code).
Used in two situations. The first is to represent an ‘external reference’ to an archetype from within another archetype or template. This supports re-use. The second use is within a template, where it is used as a slot-filler.

For a new external reference, the node_id is set in the normal way, i.e. with a new code at the specialisation level of the archetype.
For a slot-filler or a redefined external reference, the node_id is set to a specialised version of the node_id of the node being specialised, allowing matching to occur during flattening.

In all uses within source archetypes and templates, the children attribute is Void.

In an operational template, the node_id is converted to the archetype_ref, and the structure contains the result of flattening any template overlay structure and the underlying flat archetype.

h|*Inherit*
2+|`C_COMPLEX_OBJECT`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*archetype_ref*: `String`
a|Reference to archetype is being used to fill a slot or redefine an external reference. Typi-cally an ‘interface’ archetype id, i.e. identifi-er with partial version information.
|===
