=== C_COMPLEX_OBJECT_PROXY Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*C_COMPLEX_OBJECT_PROXY*

|*Description*
{set:cellbgcolor:lightblue}
2+|A constraint defined by proxy, using a reference to an object constraint defined elsewhere in the same archetype. Note that since this object refers to another node, there are two objects with available occurrences values. The local occurrences value on a COJMPLEX_OBJECT_PROXY should always be used; when setting this from a seri- alised form, if no occurrences is mentioned, the target occurrences should be used (not the standard default of {1..1}); otherwise the locally specified occurrences should be used as normal. When serialising out, if the occurrences is the same as that of the target, it can be left out. 
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|C_OBJECT
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*1..1*
{set:cellbgcolor:lightblue}
|*target_path*: `String`
{set:cellbgcolor!}
|Reference to an object node using archetype path notation.
|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*use_target_occurrences*: `Boolean` +
*_Post_*: Result = (occurrences = Void)
{set:cellbgcolor!}
|True if target occurrences are to be used as the value of occurrences in this object; by the time of runtime use, the target occurrences value has to be set into this object.
|===
