=== C_DATE_TIME Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*C_DATE_TIME*

h|*Description*
2+a|Constraint on instances of assumed primitive type Date_time. There is no validity flag for ‘year’, since it must always be by definition mandatory in order to have a sensible date/time at all. Syntax expressions of instances of this class include “YYYY-MM-DDT??:??:??” (date/time with optional time) and “YYYY-MMDDTHH:MM:xx” (date/time, seconds not allowed).

h|*Inherit*
2+|C_TEMPORAL

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1 +
(redefined)*
|*constraint*: `List<Interval<Date_time>>`
a|Formal constraint on assumed primitive type Date_time, in the form of List of Interval<Date_time>, i.e. one or more intervals of Date_time.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*month_validity*: `VALIDITY_KIND`
a|Validity of month in constrained date.

h|
|*day_validity*: `VALIDITY_KIND`
a|Validity of day in constrained date.

h|
|*timezone_validity*: `VALIDITY_KIND`
a|Validity of timezone in constrained date.

h|
|*minute_validity*: `VALIDITY_KIND`
a|Validity of minute in constrained time.

h|
|*second_validity*: `VALIDITY_KIND`
a|Validity of second in constrained time.

h|
|*millisecond_validity*: `VALIDITY_KIND`
a|Validity of millisecond in constrained time.

h|*Invariant*
2+a|*_Pattern_validity_*: pattern /= Void implies valid_iso8601_date_time_constraint_pattern(pattern)
|===
