=== C_DATE_TIME Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*C_DATE_TIME*

h|*Description*
2+a|Constraint on instances representing date/times, i.e. instants in time.

There is no validity flag for `_year_`, since it must always be by definition mandatory in order to have a sensible date/time at all. Syntax expressions of instances of this class include `"YYYY-MM-DDT??:??:??"` (date/time with optional time) and `"YYYY-MMDDTHH:MM:xx"` (date/time, seconds not allowed).

h|*Inherit*
2+|`<<_c_temporal_class,C_TEMPORAL>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1 +
(redefined)*
|*constraint*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/BASE/{base_release}/foundation_types.html#_interval_class[Interval^]<link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]>>`
a|Formal constraint on the assumed primitive `Iso8601_date_time` type, in the form of one or more `Interval<Iso8601_date_time>`.

For a pattern constraint or no constraint, use an empty list.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*month_validity* (): `link:/releases/BASE/{base_release}/base_types.html#_validity_kind_enumeration[VALIDITY_KIND^]`
a|Validity of month in constrained date.

h|*1..1*
|*day_validity* (): `link:/releases/BASE/{base_release}/base_types.html#_validity_kind_enumeration[VALIDITY_KIND^]`
a|Validity of day in constrained date.

h|*1..1*
|*timezone_validity* (): `link:/releases/BASE/{base_release}/base_types.html#_validity_kind_enumeration[VALIDITY_KIND^]`
a|Validity of timezone in constrained date.

h|*1..1*
|*minute_validity* (): `link:/releases/BASE/{base_release}/base_types.html#_validity_kind_enumeration[VALIDITY_KIND^]`
a|Validity of minute in constrained time.

h|*1..1*
|*second_validity* (): `link:/releases/BASE/{base_release}/base_types.html#_validity_kind_enumeration[VALIDITY_KIND^]`
a|Validity of second in constrained time.

h|*1..1*
|*millisecond_validity* (): `link:/releases/BASE/{base_release}/base_types.html#_validity_kind_enumeration[VALIDITY_KIND^]`
a|Validity of millisecond in constrained time.

h|*Invariants*
2+a|__Pattern_validity__: `pattern /= Void implies valid_iso8601_date_time_constraint_pattern(pattern)`
|===
