=== C_DATE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*C_DATE*

h|*Description*
2+a|Constraint on instances of `Date` in the form either of a set of validity values, or else date ranges based on the `C_ORDERED` list constraint. There is no validity flag for `_year_`, since it must always be by definition mandatory in order to have a sensible date at all. Syntax expressions of instances of this class include `"YYYY-??-??"` (date with optional month and day).

h|*Inherit*
2+|`C_TEMPORAL`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1 +
(redefined)*
|*constraint*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/BASE/{base_release}/foundation_types.html#_interval_class[Interval^]<link:/releases/BASE/{base_release}/foundation_types.html#_idate_class[IDate^]>>`
a|Formal constraint on the assumed primitive `Date` type, in the form of one or more `Interval<Date>`.

For a pattern constraint or no constraint, use an empty list.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*month_validity* (): `VALIDITY_KIND`
a|Validity of month in constrained date.

h|
|*day_validity* (): `VALIDITY_KIND`
a|Validity of day in constrained date.

h|
|*timezone_validity* (): `VALIDITY_KIND`
a|Validity of timezone in constrained date.

h|*Invariants*
2+a|*_Pattern_validity_*: `pattern /= Void implies valid_iso8601_date_constraint_pattern(pattern)`
|===
