=== C_DURATION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*C_DURATION*

h|*Description*
2+a|Constraint on instances representing duration, which is assumed to have the same parts as the ISO8601 duration string. Thus, constraints are of the form `"PWD"` (weeks and/or days), `"PDTHMS"` (days, hours, minutes, seconds) and so on.

In official ISO 8601:2004, the ‘W’ (week) designator cannot be mixed in; allowing it is an openEHR-wide exception. The allowed patterns are: `P[Y&#124;y][M&#124;m][D&#124;d][T[H&#124;h][M&#124;m][S&#124;s]] and P[W&#124;w]`.

h|*Inherit*
2+|`C_TEMPORAL`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1 +
(redefined)*
|*constraint*: `List<Interval<Iso8601_duration>>`
a|Formal constraint on the assumed primitive `Iso8601_duration` type, in the form of List of `Interval<Iso8601_duration>`, i.e. one or more intervals of `Iso8601_duration`.

h|*0..1 +
(redefined)*
|*default_value*: `Iso8601_duration`
a|Default value set in a template, and present in an operational template. Generally limited to leaf and near-leaf nodes.

h|*0..1 +
(redefined)*
|*assumed_value*: `Iso8601_duration`
a|Value to be assumed if none sent in data.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*years_allowed:* (): `Boolean`
a|True if years are allowed in the constrained Duration.

h|
|*months_allowed:* (): `Boolean`
a|True if months are allowed in the constrained Duration.

h|
|*weeks_allowed:* (): `Boolean`
a|True if weeks are allowed in the constrained Duration.

h|
|*days_allowed* (): `Boolean`
a|True if days are allowed in the constrained Duration.

h|
|*hours_allowed* (): `Boolean`
a|True if hours are allowed in the constrained Duration.

h|
|*minutes_allowed* (): `Boolean`
a|True if minutes are allowed in the constrained Duration.

h|
|*seconds_allowed* (): `Boolean`
a|True if seconds are allowed in the constrained Duration.
|===
