=== C_DURATION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*C_DURATION*

h|*Description*
2+a|Constraint on instances of assumed primitive type Duration, which is assumed to have the same parts as the ISO8601 duration string. Thus, constraints are of the form “PWD” (weeks and/or days), “PDTHMS” (days, hours, minutes, seconds) and so on.

In official ISO 8601:2004, the ‘W’ (week) designator cannot be mixed in; allowing it is an openEHR-wide exception. The allowed patterns are: P[Y&#124;y][M&#124;m][D&#124;d][T[H&#124;h][M&#124;m][S&#124;s]] and P[W&#124;w].

h|*Inherit*
2+|`C_TEMPORAL`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1 +
(redefined)*
|*constraint*: `List<Interval<Duration>>`
a|Formal constraint on assumed primitive type Duration, in the form of List of Interval<Duration>, i.e. one or more intervals of Duration.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*years_allowed:* (): `Boolean`
a|True if years are allowed in the constrained Duration.

h|
|*months_allowed:* (): `Boolean`
a|True if months are allowed in the constrained Duration.

h|
|*weeks_allowed:* (): `Boolean`
a|True if weeks are allowed in the constrained Duration.

h|
|*days_allowed* (): `Boolean`
a|True if days are allowed in the constrained Duration.

h|
|*hours_allowed* (): `Boolean`
a|True if hours are allowed in the constrained Duration.

h|
|*minutes_allowed* (): `Boolean`
a|True if minutes are allowed in the constrained Duration.

h|
|*seconds_allowed* (): `Boolean`
a|True if seconds are allowed in the constrained Duration.
|===
