=== C_OBJECT Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*_C_OBJECT (abstract)_*

h|*Description*
2+a|Abstract model of constraint on any kind of object node.

h|*Inherit*
2+|ARCHETYPE_CONSTRAINT

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*rm_type_name*: `String`
a|Reference model type that this node corresponds to.

h|*0..1*
|*occurrences*: `MULTIPLICITY_INTERVAL`
a|Occurrences of this object node in the data, under the owning attribute. Upper limit can only be greater than 1 if owning attribute has a cardinality of more than 1.
Only set if it overrides the parent archetype in the case of specialised archetypes, or else the occurrences inferred from the underlying reference model existence and/or cardinality of the containing attribute.

h|*1..1*
|*node_id*: `String`
a|Semantic identifier of this node, used to dis-tinguish sibling nodes. All nodes must have a node_id; for nodes under a container C_ATTRIBUTE, the id must be an id-code must be defined in the archetype terminolo-gy. For valid structures, all node ids are id-codes.
For C_PRIMITIVE_OBJECTs, it will have the special value Primitive_node_id.

h|*0..1*
|*is_deprecated*: `Boolean`
a|True if this node and by implication all sub-nodes are deprecated for use.

h|*0..1*
|*sibling_order*: `SIBLING_ORDER`
a|Optional indicator of order of this node with respect to another sibling. Only meaningful in a specialised archetype for a C_OBJECT within a C_ATTRIBUTE with is_multiple = True.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*specialisation_depth*: `Integer`
a|Level of specialisation of this archetype node, based on its node_id. The value 0 corresponds to non-specialised, 1 to first-level specialisation and so on. The level is the same as the number of ‘.’ characters in the node_id code. If node_id is not set, the return value is -1, signifying that the specialisation level should be determined from the nearest parent C_OBJECT node having a node_id.
|===
