=== C_ORDERED<T> Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_C_ORDERED<T> (abstract)_*

h|*Description*
2+a|Abstract parent of primitive constrainer classes based on `Ordered` base types, i.e. types like `Integer`, `Real`, and the Date/Time types. The model constraint is a List of Intervals, which may include point Intervals, and acts as a efficient and formally tractable representation of any number of point values and/or contiguous intervals of an ordered value domain.

In its simplest form, the constraint accessor returns just a single point `Interval<T>` object, representing a single value.

The next simplest form is a single proper `Interval <T>` (i.e. normal two-sided or half-open interval). The most complex form is a list of any combination of point and proper intervals.

h|*Inherit*
2+|`C_PRIMITIVE_OBJECT`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1 +
(redefined)*
|*constraint*: `List<Interval>`
a|Constraint in the form of a List of Intervals of the parameter type T. Concrete types generated in descendants via template binding.

h|*0..1 +
(redefined)*
|*default_value*: `T`
a|Default value set in a template, and present in an operational template. Generally limited to leaf and near-leaf nodes.

h|*0..1 +
(redefined)*
|*assumed_value*: `T`
a|Value to be assumed if none sent in data.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(effected)
|*any_allowed* (): `Boolean` +
 +
_Post_: `Result = constraint.is_empty`
a|True if any value (i.e. instance) of the reference model type would be allowed. Redefined in descendants.

h|(effected)
|*c_value_conforms_to* ( +
other: `C_ORDERED[1]` +
): `Boolean`
a|True if `_other.any_allowed_` or else for every constraint in the `_constraint_` list there is a constraint in `_other.constraint_` that contains it.

h|(effected)
|*c_value_congruent_to* ( +
other: `C_ORDERED[1]` +
): `Boolean`
a|True if the items in `_constraint_` are equal in number and identical pair-wise with those in `_other.constraint_`.
|===
