=== C_PRIMITIVE_OBJECT Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*_C_PRIMITIVE_OBJECT (abstract)_*

h|*Description*
2+a|Parent of types representing constraints on primitive types.

h|*Inherit*
2+|C_DEFINED_OBJECT

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*assumed_value*: `Any`
a|Value to be assumed if none sent in data.

h|*0..1*
|*is_enumerated_type_constraint*: `Boolean`
a|True if this object represents a constraint on an enumerated type from the reference model, where the latter is assumed to be based on a primitive type, generally Integer or String.

h|*1..1*
|*constraint*: `Any`
a|Constraint represented by this object; redefine in descendants.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*has_assumed_value*: `Boolean`
a|True if there is an assumed value.

h|
|*constrained_typename*: `String`
a|Generate name of native type that is constrained by this C_XXX type. For most types, it is the C_XXX typename without the 'C_', i.e. XXX. E.g. C_INTEGER -> Integer. For the date/time types the mapping is different.
|===
