=== C_PRIMITIVE_OBJECT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_C_PRIMITIVE_OBJECT (abstract)_*

h|*Description*
2+a|Parent of types representing constraints on primitive types.

h|*Inherit*
2+|`C_DEFINED_OBJECT`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*assumed_value*: `Any`
a|Value to be assumed if none sent in data.

h|*0..1*
|*is_enumerated_type_constraint*: `Boolean`
a|True if this object represents a constraint on an enumerated type from the reference model, where the latter is assumed to be based on a primitive type, generally Integer or String.

h|*1..1*
|*constraint*: `Any`
a|Constraint represented by this object; redefine in descendants.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*has_assumed_value* (): `Boolean`
a|True if there is an assumed value.

h|
|*constrained_typename* (): `String`
a|Generate name of native type that is constrained by this `C_XXX` type. For most types, it is the `C_XXX` typename without the `C_`, i.e. `XXX`. E.g. `C_INTEGER` -> `Integer`. For the date/time types the mapping is different.

h|
|*c_value_conforms_to* ( +
other: `C_PRIMITIVE_OBJECT[1]` +
): `Boolean`
a|True if this node expresses a value constraint that conforms to that of `other`. Effected in descendants.

h|
|*c_value_congruent_to* ( +
other: `C_PRIMITIVE_OBJECT[1]` +
): `Boolean`
a|True if this node expresses the same value constraint as `other`. Effected in descendants.

h|(effected)
|*c_conforms_to* ( +
other: `C_PRIMITIVE_OBJECT[1]`, +
rmcc: `FUNCTION<<String,String>,Boolean>[1]` +
): `Boolean`
a|True if constraints represented by this node, ignoring any sub-parts, are narrower or the same as other.
Typically used during validation of special-ised archetype nodes.

h|(effected)
|*c_congruent_to* ( +
other: `C_PRIMITIVE_OBJECT[1]` +
): `Boolean`
a|True if constraints represented by this node contain no further redefinitions with respect to the node `_other_`, with the exception of node_id redefnition in `C_OBJECT` nodes.

Typically used to test if an inherited node locally contains any constraints.
|===
