=== C_SECOND_ORDER Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_C_SECOND_ORDER (abstract)_*

h|*Description*
2+a|Abstract parent of classes defining second order constraints.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*members*: `List<ARCHETYPE_CONSTRAINT>`
a|Members of this second order constrainer. Normally redefined in descendants.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(abstract)*
|*c_conforms_to* ( +
other: `C_SECOND_ORDER[1]`, +
rmcc: `FUNCTION<<String,String>,Boolean>[1]` +
): `Boolean`
a|True if constraints represented by this node, ignoring any sub-parts, are narrower or the same as other. Typically used during validation of specialised archetype nodes.

.Parameters +
[horizontal]
`_rmcc_`:: RM conformance checker - a lambda (i.e. function object) that can compute conformance of type-names within the  Reference Model on which the current archetype is based. The signature provides two arguments representing respectively, the `_rm_type_name_` of the current node and the `_rm_type_name_` of the node being redefined in a specialisation parent archetype.

h|*1..1 +
(abstract)*
|*c_congruent_to* ( +
other: `C_SECOND_ORDER[1]` +
): `Boolean`
a|True if constraints represented by this node contain no further redefinitions with respect to the node other. Typically used to test if an inherited node locally contains any constraints.
|===
