=== C_TEMPORAL Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_C_TEMPORAL (abstract)_*

h|*Description*
2+a|Purpose Abstract parent of `C_ORDERED` types whose base type is an ISO date/time type.

h|*Inherit*
2+|`C_ORDERED`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*pattern_constraint*: `String`
a|Optional alternative constraint in the form of a pattern based on ISO8601. See descendants for details.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*valid_pattern_constraint* ( +
a_pattern: `String[1]` +
): `Boolean`
a|True if `_a_pattern_` is a valid constraint. Define in concrete descendants.

h|
|*valid_pattern_constraint_replacement* ( +
a_pattern: `String[1]`, +
an_other_pattern: `String[1]` +
): `Boolean`
a|Return True if `_a_pattern_` can be replaced by `_an_other_pattern_` in a specialised constraint. Define in concrete subtypes.

h|(effected)
|*any_allowed* (): `Boolean` +
*_Post_*: `Result = precursor and pattern_constraint.is_empty`
a|True if any value (i.e. instance) of the reference model type would be allowed. Redefined in descendants.

h|(effected)
|*c_value_conforms_to* ( +
other: `C_ORDERED[1]` +
): `Boolean`
a|True if precursor() or else `_other.pattern_constraint_` is empty, or else `_pattern_constraint_` is a valid (narrower) replacement for `_other.pattern_constraint_`.

h|(effected)
|*c_value_congruent_to* ( +
other: `C_ORDERED[1]` +
): `Boolean`
a|True if `precursor (other)` and `_pattern_constraint_ ~ _other.pattern_constraint_`, i.e. either both `Void` or else both non-`Void` and identical.
|===
