=== C_TERMINOLOGY_CODE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*C_TERMINOLOGY_CODE*

h|*Description*
2+a|Constrainer type for instances of `Terminology_code`. The constraint attribute can contain:

* a single at-code
* a single ac-code, representing a value-set that is defined in the archetype terminology

If there is an assumed value for the ac-code case above, the assumed_value attribute contains a single at-code, which must come from the list of at-codes defined as the internal value set for the ac-code.

h|*Inherit*
2+|`C_PRIMITIVE_OBJECT`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*constraint*: `String`
a|Type of individual constraint - a single string that can either be a local at-code, or a local ac-code signifying a locally defined value set. If an ac-code, assumed_value may contain an at-code from the value set of the ac-code.

h|*0..1 +
(redefined)*
|*assumed_value*: `Terminology_code`
a|Assumed Terminology code value.

h|*1..1 +
(redefined)*
|*default_value*: `Terminology_code`
a|
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*value_set_expanded* (): `List<String>`
a|Effective set of at-code values corresponding to an ac-code for a locally defined value set. Not defined for ac-codes that have no local value set.

h|
|*value_set_substituted* (): `List<Uri>`
a|For locally defined value sets within individual code bindings: return the term URI(s) substituted from bindings for local at-codes in `_value_set_expanded_`.

h|
|*value_set_resolved* (): `List<Terminology_code>`
a|For locally defined value sets within individual code bindings: final set of external codes to which value set is resolved.

h|(effected)
|*valid_value* ( +
a_value: `Terminology_code[1]` +
): `Boolean`
a|True if a `_value_` is valid with respect to constraint expressed in concrete instance of this type.

h|(effected)
|*prototype_value* (): `Terminology_code`
a|A generated prototype value from this constraint object.

h|(effected)
|*any_allowed* (): `Boolean` +
 +
_Post_: `Result := constraint.is_empty`
a|True if any value (i.e. instance) of the reference model type would be allowed. Redefined in descendants.

h|(effected)
|*c_value_conforms_to* ( +
other: `C_TERMINOLOGY_CODE[1]` +
): `Boolean`
a|True if `_other.any_allowed_` or else every constraint in the `_constraint_` list exists in the `_other.constraint_`.

h|(effected)
|*c_value_congruent_to* ( +
other: `C_TERMINOLOGY_CODE[1]` +
): `Boolean`
a|True if `_constraint_` and `_other.constraint_` are both value-set ids, and expand to identical value sets, or else are identical value codes.
|===
