=== C_TIME Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*C_TIME*

h|*Description*
2+a|Constraint on instances representing times in the form either of a set of validity values, or else time ranges based on the `C_ORDERED` list constraint.

There is no validity flag for `_hour_`, since it must always be by definition mandatory in order to have a sensible time at all. Syntax expressions of instances of this class include `“HH:??:xx”` (time with optional minutes and seconds not allowed).

h|*Inherit*
2+|`C_TEMPORAL`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1 +
(redefined)*
|*constraint*: `List<Interval<Iso8601_time>>`
a|Formal constraint on the assumed primitive `Iso8601_time` type, in the form of List of `Interval<Iso8601_time>`, i.e. one or more intervals of `Iso8601_time`.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*minute_validity* (): `VALIDITY_KIND`
a|Validity of minute in constrained time.

h|
|*second_validity* (): `VALIDITY_KIND`
a|Validity of second in constrained time.

h|
|*millisecond_validity* (): `VALIDITY_KIND`
a|Validity of millisecond in constrained time.

h|
|*timezone_validity* (): `VALIDITY_KIND`
a|Validity of timezone in constrained date.

h|*Invariants*
2+a|*_Pattern_validity_*: `pattern /= Void implies valid_iso8601_time_constraint_pattern (pattern)`
|===
