=== ISO8601_DURATION Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*ISO8601_DURATION*

|*Description*
{set:cellbgcolor:lightblue}
2+|Represents a period of time corresponding to a difference between two timepoints.
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|ISO8601_TYPE
{set:cellbgcolor!}

|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*years*: `Integer`
{set:cellbgcolor!}
|Number of years of nominal 365-day length.

|
{set:cellbgcolor:lightblue}
|*months*: `Integer`
{set:cellbgcolor!}
|

|
{set:cellbgcolor:lightblue}
|*days*: `Integer`
{set:cellbgcolor!}
|Number of 24 hour days.

|
{set:cellbgcolor:lightblue}
|*hours*: `Integer`
{set:cellbgcolor!}
|Number of 60 minute hours.

|
{set:cellbgcolor:lightblue}
|*minutes*: `Integer`
{set:cellbgcolor!}
|Number of 60 second minutes.

|
{set:cellbgcolor:lightblue}
|*seconds*: `Integer`
{set:cellbgcolor!}
|Number of seconds.

|
{set:cellbgcolor:lightblue}
|*fractional_seconds*: `Real`
{set:cellbgcolor!}
|Fractional seconds.

|
{set:cellbgcolor:lightblue}
|*is_decminal_sign_comma*: `Boolean`
{set:cellbgcolor!}
|True if this time has a decimal part indicated by ',' (comma) rather than '.' (period).

|
{set:cellbgcolor:lightblue}
|*weeks*: `Integer`
{set:cellbgcolor!}
|Number of 7 day weeks.

|
{set:cellbgcolor:lightblue}
|*as_string*: `String`
{set:cellbgcolor!}
|ISO8601 string for duration, in format +
* P[nnY][nnM][nnW][nnD][T[nnH][nnM][nnS]]

|
{set:cellbgcolor:lightblue}
|*valid_iso8601_duration* (s: `String`): `Boolean`
{set:cellbgcolor!}
|

|
{set:cellbgcolor:lightblue}
|*to_seconds*: `Integer`
{set:cellbgcolor!}
|Total number of seconds equivalent (including fractional) of entire duration.

|*Invariant*
{set:cellbgcolor:lightblue}
2+|*_Years_valid_*: years >= 0
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Months_valid_*: months >= 0
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Weeks_valid_*: weeks >= 0
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Days_valid_*: days >= 0
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Hours_valid_*: hours >= 0
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Minutes_valid_*: minutes >= 0
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Seconds_valid_*: seconds >= 0
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Fractional_second_valid_*: fractional_second >= 0.0 and fractional_second < 1.0
{set:cellbgcolor!}
|===
