=== ISO8601_TIME Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*ISO8601_TIME*

|*Description*
{set:cellbgcolor:lightblue}
2+|Represents an absolute point in time from an origin usually interpreted as meaning the start of the current day, specified to the second. +
NOTE: A small deviation to the ISO 8601:2004 standard in this class is that the time 24:00:00 is not allowed, for consistency with ISO8601_DATE_TIME.
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|ISO8601_TYPE
{set:cellbgcolor!}

|*Functions*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|
{set:cellbgcolor:lightblue}
|*hour*: `Integer`
{set:cellbgcolor!}
|Hour in day, in 24-hour time.

|
{set:cellbgcolor:lightblue}
|*minute*: `Integer`
{set:cellbgcolor!}
|Minute in hour.

|
{set:cellbgcolor:lightblue}
|*second*: `Integer`
{set:cellbgcolor!}
|

|
{set:cellbgcolor:lightblue}
|*fractional_second*: `Real` +
*_Pre_*: not second_unknown
{set:cellbgcolor!}
|Fractional seconds.

|
{set:cellbgcolor:lightblue}
|*has_fractional_second*: `Boolean`
{set:cellbgcolor!}
|True if the fractional_second part is signficant (i.e. even if = 0.0).

|
{set:cellbgcolor:lightblue}
|*minute_unknown*: `Boolean`
{set:cellbgcolor!}
|Indicates whether minute is unknown. If so, the time is of the form “hh”.

|
{set:cellbgcolor:lightblue}
|*second_unknown*: `Boolean`
{set:cellbgcolor!}
|Indicates whether second is unknown. If so and month is known, the time is of the form “hh:mm” or “hhmm”.

|
{set:cellbgcolor:lightblue}
|*is_decimal_sign_comma*: `Boolean`
{set:cellbgcolor!}
|True if this time has a decimal part indicated by ‘,’ (comma) rather than ‘.’ (period).

|
{set:cellbgcolor:lightblue}
|*timezone*: `ISO8601_TIMEZONE`
{set:cellbgcolor!}
|

|
{set:cellbgcolor:lightblue}
|*as_string*: `String`
{set:cellbgcolor!}
|ISO8601 string for time, i.e. in form: hhmmss[,sss][Z|hh[mm]] or the extended form: hh:mm:ss[,sss][Z|hh[mm]], or a partial invariant. See valid_iso8601_time for validity.

|
{set:cellbgcolor:lightblue}
|*valid_iso8601_time*: `Boolean`
{set:cellbgcolor!}
|String is a valid ISO 8601 date, i.e. takes the form: +
* hhmmss[,sss][Z | hh[mm]] +
or the extended form: +
* hh:mm:ss[,sss][Z | ±hh[mm]] +
or one of the partial forms: +
* hhmm or hh  +
or the extended form: +
* hh:mm +
with an additional optional timezone indicator of: +
* Z or hh[mm] +
Where: +
* hh is “00” - “23” (0-filled to two digits) +
* mm is “00” - “59” (0-filled to two digits) +
* ss is “00” - “60” (0-filled to two digits) +
* sss is any numeric string, representing an optional fractional second +
* Z is a literal meaning UTC (modern replacement for GMT), i.e. timezone +0000 +
* hh[mm], i.e. +hhmm, +hh, -hhmm, -hh indicating the timezone 

|(effected)
{set:cellbgcolor:lightblue}
|*is_partial*: `Boolean`
{set:cellbgcolor!}
|True if this time is partial, i.e. if seconds or more is missing.

|(effected)
{set:cellbgcolor:lightblue}
|*is_extended*: `Boolean`
{set:cellbgcolor!}
|True if this time uses ‘:’ separators.

|*Invariant*
{set:cellbgcolor:lightblue}
2+|*_Hour_valid_*: valid_hour(hour, minute, second)
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Minute_valid_*: not minute_unknown implies valid_minute (minute)
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Second_valid_*: not second_unknown implies valid_second (second)
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Fractional_second_valid_*: has_fractional_second implies (not second_unknown and valid_fractional_second (fractional_second))
{set:cellbgcolor!}

|
{set:cellbgcolor:lightblue}
2+|*_Partial_validity_*: minute_unknown implies second_unknown
{set:cellbgcolor!}
|===
