=== OPERATIONAL_TEMPLATE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*OPERATIONAL_TEMPLATE*

h|*Description*
2+a|Root object of an operational template. An operational template is derived from a `TEMPLATE` definition and the `ARCHETYPEs` and/or `TEMPLATE_OVERLAYs` mentioned by that template by a process of flattening, and potentially removal of unneeded languages and terminologies.

An operational template is used for generating and validating RM-canonical instance data, and also as a source artefact for generating other downstream technical artefacts, including XML schemas, APIs and UI form definitions.

h|*Inherit*
2+|`AUTHORED_ARCHETYPE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*component_terminologies*: `Hash<String, ARCHETYPE_TERMINOLOGY>`
a|Compendium of flattened terminologies of archetypes externally referenced from this archetype, keyed by archetype identifier. This will almost always be present in a template.

h|*0..1*
|*terminology_extracts*: `Hash<String,ARCHETYPE_TERMINOLOGY>`
a|Directory of term definitions as a two-level  table. The outer hash keys are term codes,  e.g. "at4", and the inner hash key are term  attribute names, e.g. "text", "description" etc.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*component_terminology* ( +
an_id: `String[1]` +
): `ARCHETYPE_TERMINOLOGY`
a|

h|*Invariants*
2+a|*_Specialisation_validity_*: `is_specialised`
|===
