=== P_ARCHETYPE Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*_P_ARCHETYPE (abstract)_*

h|*Description*
2+a|Archetype equivalent to ARCHETYPED class in Common reference model. Defines semantics of identfication, lifecycle, versioning, composition and specialisation.

An archetype is a modelled as a particular kind of AUTHORED_RESOURCE, and as such, includes descriptive meta-data, language information and revision history. The ARCHETYPE class adds identifying information, a definition - expressed in terms of constraints on instances of an object model, and an ontology.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*parent_archetype_id*: `String`
a|Identifier of the specialisation parent of this archetype.

h|*1..1*
|*archetype_id*: `P_ARCHETYPE_HRID`
a|Identifier of this archetype.

h|*1..1*
|*is_differential*: `Boolean`
a|Flag indicating whether this archetype is differential or flat in its contents. Top-level source archetypes have this flag set to True.

h|*1..1*
|*definition*: `P_C_COMPLEX_OBJECT`
a|Root node of the definition of this archetype.

h|*1..1*
|*terminology*: `P_ARCHETYPE_TERMINOLOGY`
a|The terminology of the archetype.

h|*0..1*
|*rules*: `List<STATEMENT>`
a|Rules relating to this archetype. Statements are expressed in first order predicate logic, and usually refer to at least two attributes.
|===
