=== P_AUTHORED_ARCHETYPE Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*P_AUTHORED_ARCHETYPE*

h|*Description*
2+a|Root object of a standalone, authored archetype, including all meta-data, description, other identifiers and lifecycle.

h|*Inherit*
2+|P_ARCHETYPE, AUTHORED_RESOURCE, P_AUTHORED_RESOURCE

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*adl_version*: `String`
a|ADL version if archteype was read in from an ADL sharable archetype.

h|*1..1*
|*build_uid*: `UID`
a|Unique identifier of this archetype artefact instance. A new identifier is assigned every time the content is changed by a tool. Used by tools to distinguish different revisions and/or interim snapshots of the same artefact.

h|*1..1*
|*rm_release*: `String`
a|Semver.org compatible release of the most recent reference model release on which the archetype in its current version is based. This does not imply conformance only to this release, since an archetype may be valid with respect to multiple releases of a reference model.

h|*1..1*
|*is_generated*: `Boolean`
a|If True, indicates that this artefact was machine-generated from some other source, in which case, tools would expect to overwrite this artefact on a new generation. Editing tools should set this value to False when a user starts to manually edit an archetype.

h|*1..1*
|*other_meta_data*: `Hash<String, String>`
a|
|===
