=== P_C_ATTRIBUTE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*P_C_ATTRIBUTE*

h|*Description*
2+a|Abstract model of constraint on any kind of attribute node.

h|*Inherit*
2+|`<<_p_archetype_constraint_class,P_ARCHETYPE_CONSTRAINT>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*rm_attribute_name*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Reference model attribute within the enclosing type represented by a C_OBJECT.

h|*0..1*
|*existence*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Constraint on every attribute, regardless of whether it is singular or of a container type, which indicates whether its target object exists or not (i.e. is mandatory or not).

h|*0..1*
|*children*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<<<_p_c_object_class,P_C_OBJECT>>>`
a|Child C_OBJECT nodes. Each such node represents a constraint on the type of this attribute in its reference model. Multiples occur both for multiple items in the case of container attributes, and alternatives in the case of singular attributes.

h|*0..1*
|*differential_path*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Within a differential specialised archetype, may be set to represent a deep path within the structure to which this constraint and its child constraints apply.

h|*0..1*
|*cardinality*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Cardinality constraint of attribute, if a container attribute.

h|*1..1*
|*is_multiple*: `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Flag indicating whether this attribute constraint is on a container (i.e. multiply-valued) attribute.
|===
