=== P_C_TERMINOLOGY_CODE Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*P_C_TERMINOLOGY_CODE*

|*Description*
{set:cellbgcolor:lightblue}
2+|Constrainer type for instances of TERMINOLOGY_CODE. The primary expression of the constraint is in the property `tuple_constraint', and comes in 3 variations: +
* a single at-code +
* a single ac-code, representing a value-set that is defined in the archetype terminology +
* a list of at- and/or ac-codes, representing the possibilities of a tuple constraint +
The last possibility above is enabled by the merge_tuple routine, which enables the constraint of another single-valued C_TERMINOLOGY_CODE to be merged with the current one.
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|P_C_PRIMITIVE_OBJECT
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*1..1 +
(redefined)*
{set:cellbgcolor:lightblue}
|*constraint*: `String`
{set:cellbgcolor!}
|

|*0..1 +
(redefined)*
{set:cellbgcolor:lightblue}
|*assumed_value*: `TERMINOLOGY_CODE`
{set:cellbgcolor!}
|

|*1..1 +
(redefined)*
{set:cellbgcolor:lightblue}
|*default_value*: `TERMINOLOGY_CODE`
{set:cellbgcolor!}
|
|===
