=== P_OPERATIONAL_TEMPLATE Class

[cols="^1,2,3"]
|===
|*Class*
{set:cellbgcolor:lightblue}
2+^|*P_OPERATIONAL_TEMPLATE*

|*Description*
{set:cellbgcolor:lightblue}
2+|Root object of an operational template. An operational template is derived from a TEMPLATE definition and the ARCHETYPEs and/or TEMPLATE_OVERLAYs mentioned by that template by a process of flattening, and potentially removal of unneeded languages and terminologies. +
An operational template is used for generating and validating canonical openEHR data, and also as a source artefact for generating other downstream technical artefacts, including XML schemas, APIs and UI form definitions.
{set:cellbgcolor!}

|*Inherit*
{set:cellbgcolor:lightblue}
2+|P_AUTHORED_ARCHETYPE
{set:cellbgcolor!}

|*Attributes*
{set:cellbgcolor:lightblue}
^|*Signature*
^|*Meaning*

|*0..1*
{set:cellbgcolor:lightblue}
|*component_terminologies*: `List<P_ARCHETYPE_TERMINOLOGY>`
{set:cellbgcolor!}
|Compendium of flattened terminologies of archetypes externally referenced from this archetype, keyed by archetype identifier. This will almost always be present in a template.

|*0..1*
{set:cellbgcolor:lightblue}
|*terminology_extracts*: `Hash<Hash<ARCHETYPE_TERM, String>, String>`
{set:cellbgcolor!}
|Directory of term definitions as a two-level  table. The outer hash keys are term codes,  e.g. "at4", and the inner hash key are term  attribute names, e.g. "text", "description" etc.
|===
