=== TERMINOLOGY_SERVICE Class

[cols="^1,2,3"]
|===
h|*Class*
2+^h|*TERMINOLOGY_SERVICE*

h|*Description*
2+a|Defines an object providing proxy access to a terminology service. 

h|*Inherit*
2+|OPENEHR_TERMINOLOGY_GROUP_IDENTIFIERS, OPENEHR_CODE_SET_IDENTIFIERS

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*terminology* (name): `TERMINOLOGY_ACCESS` +
*_Pre_*: has_terminology (name)
a|Return an interface to the terminology named name. Allowable names include:-

* openehr  
* centc251  
* any name from are taken from the US NLM UMLS meta-data list at http://www.nlm.nih.gov/research/umls/metaa1.html 

h|
|*code_set* (name): `CODE_SET_ACCESS` +
*_Pre_*: has_code_set (name)
a|Return an interface to the code_set identified by the external identifier name (e.g.  ISO_639-1 ). 

h|
|*code_set_for_id* (id): `CODE_SET_ACCESS` +
*_Pre_*: valid_code_set_id (id)
a|Return an interface to the code_set identified internally in openEHR by id. 

h|
|*has_terminology* (name): `boolean`
a|True if terminology named name known by this service. Allowable names include:-

* openehr  
* centc251  
* any name from are taken from the US NLM UMLS meta-data list at http://www.nlm.nih.gov/research/umls/metaa1.html

h|
|*has_code_set* (name): `boolean`
a|True if code_set linked to internal name (e.g.  languages ) is available. 

h|
|*terminology_identifiers*: 
a|Set of all terminology identifiers known in the terminology service. Values from 
the US NLM UMLS meta-data list at:-

http://www.nlm.nih.gov/research/umls/metaa1.html 

h|
|*openehr_code_sets*: `Hash<String, String>`
a|Set of all code set identifiers known in the terminology service. 

h|
|*code_set_identifiers*: 
a|Set of all code sets identifiers for which there is an internal openEHR name; returned as a Map of ids keyed by internal name. 
|===
