= The Cooked Operational Template

A 'cooked' OPT is a technical artefact intended for direct use in some context. It is a processed form of the raw OPT in which various removals of unwanted elements are made, and terminology references are converted to the desired form for final use.

It is assumed that tools provide ways of specifying the various alterations, and they are not described here. the following describes only the resulting output.

== Annotations Removal

Annotations can be removed from a raw OPT, which results in the complete removal of the `annotations` section in the output.

== Language Filtering

Since archetypes and templates in general may contain numerous language translations, and the target deployment environment is normally targetted to only one or two languages, one of the filtering possibilities is to remove any of the languages (including the original authoring language) up to the limit where only one remains.

The resulting OPT will be of the same form as before, but with reduced language translations. In the `language` section of the archetype, the `original_language` property will either contain the original authoring language of the root source template (which could easily be different from that of the majority of referenced archetypes).

== Terminology Filtering

Terminology bindings can also be filtered out in the cooked OPT, up to removal of all bindings. The resulting OPT will contain only those bindings not specified for removal in the `terminology` section.

== Terminology Substitution

A more complex aspect of terminology-related processing has to do with what final codes will be used in archetype data. In the source artefacts, two types of value coding occur. The first case is fields constrained with archetype local value sets, i.e. where the ac-code maps to a group of at-codes, or a single at-code is specified. The second case is where ac-codes are bound only to external value sets (often large ones, such as 'type of infection'), and the value recorded in the data for that field must be an external code of some kind.

The first case poses a possible choice - either archetype-local at-codes or external codes could be used. The choice of what terminology should be used for each ac-code that is bound to both an internal and an external terminology can be made in the OPT, by using a modified form of the normal term constraint syntax. This is described in detail in the ADL specification, in the http://www.openehr.org/releases/AM/latest/docs/ADL2/ADL2.html#cADL_Terminology_Constraints[Terminology Constraints] and http://www.openehr.org/releases/AM/latest/docs/ADL2/ADL2.html#terminology_integration_concrete_codes[Terminology Integration] sections. Note that the choice of terminology binding is on a field by field basis, since different nodes may have value sets from different terminologies. Tooling may provide efficient ways to choose which terminologies to use.
