= Introduction

== Purpose

This document provides an explanatory guide to openEHR templates. The formal semantics are defined as part of the Archetype Object Model (AOM; see <<openehr_am_aom>>).

The document is primarily aimed at software developers and data managers.

== Related Documents

Prerequisite documents for reading this document include:

* The openEHR Architecture Overview (<<openehr_overview>>);
* The openEHR Archetypes Technical Overview (<<openehr_am_overview>>).

Related documents include:

* The openEHR Definition Language (<<openehr_am_adl>>);
* The openEHR Operational Template Specification

== Status

This specification is in the Development state. The development version of this document can be found at http://www.openehr.org/releases/trunk/architecture/am/Templates.pdf.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the http://lists.openehr.org/mailman/listinfo/openehr-technical_lists.openehr.org[technical mailing list], or on the https://openehr.atlassian.net/browse/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].

== Tools

Various tools exist for creating and processing archetypes. The http://www.openehr.org/downloads/ADLworkbench/home[ADL Workbench] is a reference compiler, visualiser and editor. The openEHR tools can be http://www.openehr.org/downloads/modellingtools[downloaded from the website] .
Source projects can be found at the https://github.com/openEHR[openEHR Github project].
