include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Primary Author

* Thomas Beale, Ocean Informatics UK; openEHR Architecture Review Board (ARB)

=== Contributors

Thanks to Sebastian Garde, Central Qld University, Australia, for German translations.

=== Trademarks

* 'Microsoft' and '.Net' are registered trademarks of the Microsoft Corporation.
* 'Java' is a registered trademark of Oracle Corporation
* 'Linux' is a registered trademark of Linus Torvalds.
* 'openEHR' is a registered trademark of The openEHR Foundation
* 'SNOMED CT' is a registered trademark of IHTSDO

=== Supporters

The work reported in this paper has been funded by the following organisations:

* UCL (University College London) - Centre for Health Informatics and Multiprofessional Education (CHIME);
* Ocean Informatics.

Special thanks to Prof David Ingram, founding Director of CHIME, UCL, who provided a vision and collegial working environment ever since the days of GEHR (1992).
== Conformance

Conformance of a data or software artifact to an openEHR specification is determined by a formal test of that artifact against the relevant {openehr_its_component}[openEHR Implementation Technology Specification(s) (ITSs)^], such as an IDL interface or an XML-schema. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.

== Tools

Various tools exist for creating and processing archetypes. The {openehr_awb}[ADL Workbench^] is a reference compiler, visualiser and editor. The openEHR tools can be {modelling_tools}[downloaded from the website^] .

Source projects can be found at the {openehr_git}[openEHR Github project^].

:sectnums!:

include::partial$amendment_record.adoc[]
