include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Primary Author

* Thomas Beale, Ocean Informatics UK; openEHR Architecture Review Board (ARB)

=== Contributors

Thanks to Sebastian Garde, Central Qld University, Australia, for German translations.

=== Trademarks

* 'Microsoft' and '.Net' are registered trademarks of the Microsoft Corporation.
* 'Java' is a registered trademark of Oracle Corporation
* 'Linux' is a registered trademark of Linus Torvalds.
* 'openEHR' is a registered trademark of The openEHR Foundation
* 'SNOMED CT' is a registered trademark of IHTSDO

=== Supporters

The work reported in this paper has been funded by the following organisations:

* UCL (University College London) - Centre for Health Informatics and Multiprofessional Education (CHIME);
* Ocean Informatics.

Special thanks to Prof David Ingram, founding Director of CHIME, UCL, who provided a vision and collegial working environment ever since the days of GEHR (1992).
== Tools

Various tools exist for creating and processing archetypes. The http://www.openehr.org/downloads/ADLworkbench/home[ADL Workbench] is a reference compiler, visualiser and editor. The openEHR tools can be http://www.openehr.org/downloads/modellingtools[downloaded from the website] .
Source projects can be found at the https://github.com/openEHR[openEHR Github project].

:sectnums!:

include::partial$amendment_record.adoc[]
